### ISSUE TITLE
FairSoft Installation Fails on OSX Mojave

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#114]
Dear FairSoft Experts,
for me the installation of FairSoft fails on the newly updated OSX Mojave.
At the beginning I had to install openssl via brew and set the OPENSSL_ROOT_DIR otherwise the cmake configuration was not working.
After that the installation of Geant4OptionalComponents fails with the following error message:

```
*** Compiling Geant4-lib ................
*** Package Geant4-build is OK ***
CMake Error at cmake/Modules/Geant4OptionalComponents.cmake:121 (if):
  if given arguments:

    "VERSION_LESS" "2.0.1"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/Modules/G4CMakeMain.cmake:59 (include)
  CMakeLists.txt:56 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/tstockmanns/PandaSoftware/FairSoft/dev/source/transport/geant4/build/CMakeFiles/CMakeOutput.log".
See also "/Users/tstockmanns/PandaSoftware/FairSoft/dev/source/transport/geant4/build/CMakeFiles/CMakeError.log".
CMake Error at cmake/Modules/Geant4OptionalComponents.cmake:121 (if):
  if given arguments:

    "VERSION_LESS" "2.0.1"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/Modules/G4CMakeMain.cmake:59 (include)
  CMakeLists.txt:56 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/tstockmanns/PandaSoftware/FairSoft/dev/source/transport/geant4/build/CMakeFiles/CMakeOutput.log".
See also "/Users/tstockmanns/PandaSoftware/FairSoft/dev/source/transport/geant4/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/G4ABLA: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/G4EMLOW: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/G4ENSDFSTATE: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/G4NDL: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/G4NEUTRONXS: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/G4PII: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/G4SAIDDATA: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/PhotonEvaporation: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/RadioactiveDecay: No such file or directory
ln: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4/data/RealSurface: No such file or directory
scripts/install_geant4.sh: line 128: /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/share/Geant4-10.4.1/geant4make/geant4make.sh: No such file or directory
*** ERROR: geant4 could not be created.
*** End installation of external packages with Errors***
```

**Comment by TobiasStockmanns** [comment]
The error does not exists when I switch off debug and optimization but I cannot tell which one is the reason for the problem.

The next error I get is in the compilation of geant3. It seems that it has a problem with gcc8.

*** Compiling Geant3 ................
mkdir: build: File exists
-- Found ROOT 6.12/06 in /Users/tstockmanns/PandaSoftware/FairSoft/dev/build
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tstockmanns/PandaSoftware/FairSoft/dev/source/transport/geant3/build
[  0%] Building Fortran object CMakeFiles/geant321.dir/gcalor/gcalor.F.o
[  0%] Building CXX object CMakeFiles/geant321.dir/TGeant3/TGeant3TGeo.cxx.o
[  0%] Building CXX object CMakeFiles/geant321.dir/TGeant3/TGeant3f77.cxx.o
[  0%] Building CXX object CMakeFiles/geant321.dir/TGeant3/TGeant3gu.cxx.o
[  0%] Building CXX object CMakeFiles/geant321.dir/comad/gcadd.cxx.o
/Users/tstockmanns/PandaSoftware/FairSoft/dev/source/transport/geant3/gcalor/gcalor.F:3221:18:

    40 CALL CERROR('CALSGM1$')
                  1
Error: Actual argument contains too few elements for dummy argument 'carg' (8/50) at (1)
/Users/tstockmanns/PandaSoftware/FairSoft/dev/source/transport/geant3/gcalor/gcalor.F:3230:37:

**Comment by MohammadAlTurany** [comment]
HI @TobiasStockmanns 

This is already fixed in Geant3 v2-5-gcc8 could you check that you have this version.

**Comment by TobiasStockmanns** [comment]
Manually taking v2-5-gcc8 from the repository solved the problem.
