### ISSUE TITLE
ZeroMQ Installation problem

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#118]
Dear FairSoft developers,
I try to install FairSoft/dev on an OpenSuse 42.3 machine. Unfortunately it fails with the following error messages:

*** Compiling zeromq ................
error: pathspec 'v4.2.5-fairroot' did not match any file(s) known to git.
-- Using tweetnacl for CURVE security
-- Detected epoll polling method
-- Detected ZMQ Version - 4.2.2
-- Checking whether EFD_CLOEXEC is supported
-- Checking whether SOCK_CLOEXEC is supported
-- Checking whether SO_KEEPALIVE is supported
-- Checking whether TCP_KEEPCNT is supported
-- Checking whether TCP_KEEPIDLE is supported
-- Checking whether TCP_KEEPINTVL is supported
-- Checking whether TCP_KEEPALIVE is supported
-- Checking whether TIPC is supported
-- Could NOT find AsciiDoc (missing: ASCIIDOC_EXECUTABLE)
CMake Error: File /home/panda/PandaSoftware/FairSoft/dev/FairSoft_source/basics/zeromq/ZeroMQConfig.cmake.in does not exist.
CMake Error at /home/panda/PandaSoftware/FairSoft/dev/FairSoft_install/share/cmake-3.9/Modules/CMakePackageConfigHelpers.cmake:312 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:920 (configure_package_config_file)

-- Configuring incomplete, errors occurred!
See also "/home/panda/PandaSoftware/FairSoft/dev/FairSoft_source/basics/zeromq/build/CMakeFiles/CMakeOutput.log".
See also "/home/panda/PandaSoftware/FairSoft/dev/FairSoft_source/basics/zeromq/build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'install'.  Stop.
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]

**** Checking libraries in /home/panda/PandaSoftware/FairSoft/dev/FairSoft_install/lib ****
*** ERROR: zeromq could not be created.
*** End installation of external packages with Errors***

**Comment by MohammadAlTurany** [comment]
HI Tobias,
Which version of FairSoft you are trying to install? It seems that you have an old installation of CMake in the FairSoft_install directory (cmake-3.9) recent Fairsoft comes with 3.11

**Comment by TobiasStockmanns** [comment]
Hi Mohammad,

I am on the latest dev branch. The last commit in git log is from 16.10.2018 : 8d0485b88fc
git pull says: Alread up-to-date

Cheers, Tobias

**Comment by fuhlig1** [comment]
Hi Tobias,

could it be that you reused an already existing installation directory.
