### ISSUE TITLE
Fairsoft

### ISSUE THREAD

**Issue by lattery** [FairRootGroup/FairSoft#126]
Following directions at:
https://panda-wiki.gsi.de/foswiki/bin/view/Computing/PandaRootInstallGit

Attempting to install the may18 branch of FairSoft…

When I do configure.sh, it works up until the point that it attempts to decompress "HepMC-2.06.09.tar.gz", stating that it is unable to do so. 
Reading the output of "file HepMC-2.06.09.tar.gz" states that it is a binary file, not a gzipped file. This is not expected.

The "functions.sh" script pulls HepMC-2.06.09.tar.gz file from a URL variable. That URL leads to an old repository for it, rather than http://hepmc.web.cern.ch/hepmc/releases/hepmc2.06.09.tgz
which is the current development page for it, as far as I can tell. 

The location where the version of HepMC is specified is:
fairsoft_may18/scripts/package_versions.sh

The relevant section of that file is this line where HepMC url is defined:
export HEPMC_LOCATION="http://lcgapp.cern.ch/project/simu/HepMC/download
export HEPMCVERSION=2.06.09

Thanks for any help you can offer.

**Comment by fuhlig1** [comment]
Hi,

unfortunately the URL isn’t valid any longer. Since last week there is a new FairSoft may18p1 which fixes the issue. Please use the new tag and inform someone who can update the wiki page.

Ciao

Florian

**Comment by rbx** [comment]
Can we have the fix also in the dev?

**Comment by fuhlig1** [comment]
Fixed also in the dev branch with  f118258

**Comment by fuhlig1** [comment]
@lattery,

does the FairSoft release may18p1 fixes your issue?

**Comment by lattery** [comment]
Yes, everything is working fine. Thank you.
