### ISSUE TITLE
installation of python bindings for G4 fail

### ISSUE THREAD

**Issue by spflueger** [FairRootGroup/FairSoft#130]
I cannot install fairsoft, because in the installation of the python bindings for geant4 files that do not exist are trying to be installed/copied. I'm using this version fairsoft https://github.com/FairRootGroup/FairSoft/releases/tag/may18p1 with gcc 8.1.0 and cmake 3.11.4.

> CMake Error at source/python3/cmake_install.cmake:51 (file):
>   file INSTALL cannot find
>   "/lustre/miifs05/scratch/him-specf/paluma/fairsoft/FairSoft-may18p1/transport/geant4/build_g4py/source/python3/__init__.pyc".
> Call Stack (most recent call first):
>   source/cmake_install.cmake:58 (include)
>   cmake_install.cmake:42 (include)
> 
> 
> make: *** [install] Error 1
> **** Checking libraries in /lustre/miifs05/scratch/him-specf/paluma/fairsoft/may18p1/lib ****
> *** ERROR: g4py could not be created.
> *** End installation of external packages with Errors***
>

**Comment by fuhlig1** [comment]
Hi,

do you need the python bindings? If you don’t need python please disable the build of any python related stuff in the configuration. Simply change the file config.cache and set the option

build_python=no

If you need python please send some more information like OS and OS version and compiler. Since I see that in the error message  the error is about python3 can you add also more information about your python setup.

Ciao

Florian

**Comment by spflueger** [comment]
Hi Florian,

I think I don't need python bindings. Turning the python build off helps with the geant4 installation, but now the installation crashes at Millepede.

```
*** Downloading MillepedeII sources with subversion***
svn: E200030: disk I/O error, executing statement 'PRAGMA synchronous=OFF;PRAGMA recursive_triggers=ON;'
*** Compiling Millepede ................ 
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- Makefile_old	2013-10-07 11:23:29.142866782 +0200
|+++ Makefile	2013-10-07 11:25:51.787284113 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat ‘/lustre/miifs05/scratch/him-specf/paluma/fairsoft/FairSoft-may18p1/basics/MillepedeII/pede’: No such file or directory
-- The Fortran compiler identification is GNU 8.1.0
-- Check for working Fortran compiler: /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/gfortran
-- Check for working Fortran compiler: /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/gfortran supports Fortran 90
-- Checking whether /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/gfortran supports Fortran 90 -- yes
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/gcc
-- Check for working C compiler: /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/g++
-- Check for working CXX compiler: /cluster/easybuild/broadwell/software/compiler/GCCcore/8.1.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:13 (add_library):
  Cannot find source file:

    Mille.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:13 (add_library):
  No SOURCES given to target: Mille


-- Build files have been written to: /lustre/miifs05/scratch/him-specf/paluma/fairsoft/FairSoft-may18p1/basics/MillepedeII/build
make: *** No rule to make target `install'.  Stop.
*** ERROR: Millepede could not be created.
*** End installation of external packages with Errors***
```

I almost have the feeling I forgot something. Did the svn command change in this version?

Information about system (let me know if you need more):
OS: CentOS Linux release 7.3.1611 (Core) 
compiler: gcc version 8.1.0 (GCC)
cmake: cmake version 3.11.4
svn: svn, version 1.7.14 (r1542130)
git: git version 1.8.3.1

Cheers

**Comment by fuhlig1** [comment]
For me it looks like there was a problem when getting the sources with „svn“. Could you please remove the directory basics/MillepedeII and rerun configure.sh again.

Ciao

Florian




> Am 18.03.2019 um 03:30 schrieb spflueger <notifications@github.com>:
> 
> *** Downloading MillepedeII sources with subversion***
> svn: E200030: disk I/O error, executing statement 'PRAGMA synchronous=OFF;PRAGMA recursive_triggers=ON;'
>

**Comment by spflueger** [comment]
That did not help, but because I'm trying to install fairsoft on the cluster at HIM, it seems to be related to the lustre filesystem.
https://www.svnforum.org/forum/opensource-subversion-forums/apache-subversion-1-8-support/80218-subversion-checkout-on-distrubuted-filesytem

**Comment by fuhlig1** [comment]
If it is the file system I am out. I was wondering that only Millepede showed this problem but I realized that is the only svn package left.

As a workaround you could checkout the svn repository somewhere else and copy the directory to the final destination.

  svn co http://svnsrv.desy.de/public/MillepedeII/tags/V04-03-10 MillepedeII

Ciao

Florian

**Comment by spflueger** [comment]
Ok, thank you. I will try

**Comment by spflueger** [comment]
Ok, now the compilation fails at the dds installation:

> error: undefined reference to 'shm_open'

Adding the linker flag -lrt fixes this problem.
