### ISSUE TITLE
dev installation of gtest fails

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#131]
Dear FairSoft developers,

I did not manage to compile the dev version of FairSoft on my Suse Linux machine. It stops with the following log output during the installation of gtest:

The build process for the external packages for the FairRoot Project was started at 260319_144018

Use these cached settings:

compiler=gcc
debug=yes
optimize=yes
build_MQOnly=no
geant4_download_install_data_automatic=yes
geant4_install_data_from_dir=no
geant4mt=no
build_root6=yes
build_python=yes
install_sim=yes
SIMPATH_INSTALL=/home/panda/PandaSoftware/FairSoft/dev/FairSoft_build
platform=linux

Ok [Y/n]:
*** Compiling the external packages with the GCC compiler
*** Building the libraries with best optimization and debug information
----------------- Install FairSoft ---------------
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found GCC Version >= 4.8
-- Found all necessary compilers.
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found all necessary X11 features.
-- Found OpenGL: /usr/lib64/libGL.so
-- Found all necessary OpenGL features.
-- Found CURL: /usr/lib64/libcurl.so (found version "7.37.0")
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2j")
-- Found all necessary programs in PATH.
-- Performing Test HAS_CXX11
-- Performing Test HAS_CXX11 - Success
-- Current compiler does suppport -std=c++11 option.
-- Performing Test HAS_LIBCXX
-- Performing Test HAS_LIBCXX - Failed
-- Current compiler does not suppport -stdlib=libc++
-- Found PythonInterp: /usr/bin/python (found version "2.7.13")
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.13")
-- Found Subversion: /usr/bin/svn (found version "1.9.7")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/panda/PandaSoftware/FairSoft/dev/FairSoft_source/test/build
The following parameters are set.
System              :  64bit
C++ compiler        :  g++
C compiler          :  gcc
Fortran compiler    :  gfortran
CXXFLAGS            :  -g -O3 -std=c++11
CFLAGS              :  -g -O3
FFLAGS              :  -g -O3
CMAKE BUILD TYPE    :  RelWithDebInfo
Compiler            :  gcc
Fortran compiler    :  gfortran
Debug               :  yes
Optimization        :  yes
Platform            :  linux
Architecture        :  linuxx8664gcc
G4System            :  Linux-g++
g4_data_files       :
g4_get_data         :
build G4 with MT    :  no
Number of parallel
processes for build :  8
Installation Directory:  /home/panda/PandaSoftware/FairSoft/dev/FairSoft_build
*** CMake compiled successfully ***
*** Compiling gtest ................
-- Configuring done
-- Generating done
-- Build files have been written to: /home/panda/PandaSoftware/FairSoft/dev/FairSoft_source/basics/gtest/build
make: *** No rule to make target 'install'.  Schluss.
**** Checking libraries in /home/panda/PandaSoftware/FairSoft/dev/FairSoft_build/lib ****
*** ERROR: gtest could not be created.
*** End installation of external packages with Errors***

**Comment by TobiasStockmanns** [comment]
Confirmed on OSX 10.14.4

**Comment by fuhlig1** [comment]
Hi Tobias,

I could not test with macOS 10.14 but for me it worked on 10.13 and 10.12. I also did a test with OpenSuse 15.0.
The output of the gtest installation is below. Which OpenSuse distribution do you use?

Could you please remove the directory

  basics/googletest-release-1.8.1

and the link

  basics/gtest

rerun the configure script and send the complete output from the gtest installation.

Ciao

Florian

--

    virtualbox-ovf: *** Unpacking release-1.8.1.tar.gz ..............
    virtualbox-ovf: *** Compiling gtest ................
    virtualbox-ovf: -- The C compiler identification is GNU 7.3.1
    virtualbox-ovf: -- The CXX compiler identification is GNU 7.3.1
    virtualbox-ovf: -- Check for working C compiler: /usr/bin/gcc
    virtualbox-ovf: -- Check for working C compiler: /usr/bin/gcc -- works
    virtualbox-ovf: -- Detecting C compiler ABI info
    virtualbox-ovf: -- Detecting C compiler ABI info - done
    virtualbox-ovf: -- Detecting C compile features
    virtualbox-ovf: -- Detecting C compile features - done
    virtualbox-ovf: -- Check for working CXX compiler: /usr/bin/g++
    virtualbox-ovf: -- Check for working CXX compiler: /usr/bin/g++ -- works
    virtualbox-ovf: -- Detecting CXX compiler ABI info
    virtualbox-ovf: -- Detecting CXX compiler ABI info - done
    virtualbox-ovf: -- Detecting CXX compile features
    virtualbox-ovf: -- Detecting CXX compile features - done
    virtualbox-ovf: -- Found PythonInterp: /usr/bin/python (found version "2.7.14")
    virtualbox-ovf: -- Looking for pthread.h
    virtualbox-ovf: -- Looking for pthread.h - found
    virtualbox-ovf: -- Looking for pthread_create
    virtualbox-ovf: -- Looking for pthread_create - not found
    virtualbox-ovf: -- Check if compiler accepts -pthread
    virtualbox-ovf: -- Check if compiler accepts -pthread - yes
    virtualbox-ovf: -- Found Threads: TRUE
    virtualbox-ovf: -- Configuring done
    virtualbox-ovf: -- Generating done
    virtualbox-ovf: -- Build files have been written to: /opt/fairsoft/source/dev/basics/gtest/build
    virtualbox-ovf: Scanning dependencies of target gtest
    virtualbox-ovf: [ 12%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
    virtualbox-ovf: [ 25%] Linking CXX static library libgtest.a
    virtualbox-ovf: [ 25%] Built target gtest
    virtualbox-ovf: Scanning dependencies of target gmock
    virtualbox-ovf: [ 37%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
    virtualbox-ovf: [ 50%] Linking CXX static library libgmock.a
    virtualbox-ovf: [ 50%] Built target gmock
    virtualbox-ovf: Scanning dependencies of target gmock_main
    virtualbox-ovf: [ 62%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
    virtualbox-ovf: [ 75%] Linking CXX static library libgmock_main.a
    virtualbox-ovf: [ 75%] Built target gmock_main
    virtualbox-ovf: Scanning dependencies of target gtest_main
    virtualbox-ovf: [ 87%] Building CXX object googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
    virtualbox-ovf: [100%] Linking CXX static library libgtest_main.a
    virtualbox-ovf: [100%] Built target gtest_main
    virtualbox-ovf: Install the project...
    virtualbox-ovf: -- Install configuration: "Release"

**Comment by TobiasStockmanns** [comment]
Problem was a left over folder with gtest 1.7.0 which was not removed after a switch to the dev branch of FairSoft.
After removing the folder, the installation is working.
