### ISSUE TITLE
DDS with may18p1 won't compile on Himster2 without -DCMAKE_CXX_FLAGS="-lrt“

### ISSUE THREAD

**Issue by rklasen** [FairRootGroup/FairSoft#132]
Hi,

as the title says, DDS won't compile unless cmake is given the explicit flag `-DCMAKE_CXX_FLAGS="-lrt“`. I suspect the library has to be added to the corresponding `CmakeLists.txt`, but I don't know where.

**Comment by dennisklein** [comment]
Can you show the build log, so we can see which DDS target breaks?
