### ISSUE TITLE
Install clang for C++14 support?

### ISSUE THREAD

**Issue by klenze** [FairRootGroup/FairSoft#136]
Dear Devs,
While writing code, I happened to note that rather useful C++14 Features (generic lambdas, deduced return types), which have been working in both clang and gcc for more than five years, are not usable in downstream projects because we only require C++11. 
This can be easily fixed locally by inserting a 
set(CMAKE_CXX_FLAGS -std=c++14)
in the downstream project CMakeList.txt after the check_compiler() call, but my colleagues might be unappreciative of me unilaterally increasing compiler dependencies. 
Is it feasible either to add C++14 compatibility as a requirement for FairSoft/FairRoot or just to package a decent C++ compiler (like clang), just like we already package a lot non-physics software (like cmake, gsl, boost) in FairSoft? This would mean one could directly jump to C++17. 
Given that FairSoft takes more than six Gigabytes on my system, another one or so for clang+llvm might not seem so bad. 
If you would be interested, I could try my luck at writing a clang install script for FairSoft.

**Comment by dennisklein** [comment]
The proper way of setting the std flag with cmake would be `CMAKE_CXX_STANDARD`.

We plan to migrate to C++17 when GCC releases a stable C++17 implementation.

[AliceO2](https://github.com/AliceO2Group/AliceO2) is a FairRoot based project, I know of, that compiles everything with C++17 successfully for a while already.

Shipping a compiler with FairSoft is probably not going to happen any more in its remaining lifetime. We are currently looking into migrating FairSoft to [spack](https://spack.io), which has proper multiple compiler support. If you are interested in contributing to this migration effort, I recommend talking to @MohammadAlTurany.

**Comment by klenze** [comment]
Thanks for the info, I will try to use CMAKE_CXX_STANDARD.
