### ISSUE TITLE
Installation problems of root with OSX Mojave (10.14.5)

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#147]
Dear all,
I have again a problem installing FairSoft on OSX Mojave (10.14.5). It sounds like issue #114 but the fix by using no optimization and debug does not work for me now.
Does anyone have an idea?

Cheers,
Tobias
[Install_100719_215150.log](https://github.com/FairRootGroup/FairSoft/files/3380880/Install_100719_215150.log)

*** Compiling root ................
mkdir: build_for_fair: File exists
Copied rootconfig.sh ......................
Configure Root ..........................................
macosx64
-- ROOT default compression algorithm: zlib
-- Found a Mac OS X System 10.14
-- Found a 64bit system
-- Found LLVM compiler collection
-- ROOT Platform: macosx
-- ROOT Architecture: macosx64
-- Build Type: Release
-- Compiler Flags: -g -O3 -Wc++11-narrowing -Wsign-compare -Wsometimes-uninitialized -Wconditional-uninitialized -Wheader-guard -Warray-bounds -Wcomment -Wtautological-compare -Wstrncat-size -Wloop-analysis -Wbool-conversion -m64 -pipe -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -std=c++11 -stdlib=libc++ -DR__HAVE_CONFIG
-- Looking for ZLib
-- Building freetype version 2.6.1 included in ROOT itself
-- Looking for PCRE
-- Looking for LZMA
-- Found LZMA includes at /usr/local/include
-- Found LZMA library at /usr/local/lib/liblzma.dylib
-- Could NOT find GIF (missing: GIF_LIBRARY GIF_INCLUDE_DIR)
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Building AfterImage library included in ROOT itself
-- Looking for GSL
-- Looking for python
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.16")
CMake Error at cmake/modules/SearchInstalledSoftware.cmake:480 (message):
  Version mismatch between Python interpreter (2.7.16) and libraries
  (2.7.10).

  ROOT cannot work with this configuration.  Please specify only
  PYTHON_EXECUTABLE to CMake with an absolute path to ensure matching
  versions are found.
Call Stack (most recent call first):
  CMakeLists.txt:150 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/tstockmanns/PandaSoftware/FairSoft/jun19/source/tools/root/build_for_fair/CMakeFiles/CMakeOutput.log".
See also "/Users/tstockmanns/PandaSoftware/FairSoft/jun19/source/tools/root/build_for_fair/CMakeFiles/CMakeError.log".
make: *** No rule to make target `install'.  Stop.
**** Checking libraries in /Users/tstockmanns/PandaSoftware/FairSoft/jun19/build/lib ****
*** ERROR: root could not be created.
 create a symbolic linking for  Vc library ....
scripts/install_root6.sh: line 69: cd: /Users/tstockmanns/PandaSoftware/FairSoft/jun19/build/lib/root: No such file or directory
ln: ./libVc.a: File exists
---link created ---
*** End installation of external packages with Errors***

**Comment by fuhlig1** [comment]
Hi Tobias,

you have a strange Python installation on your system. The python interpreter is found in /usr/local/bin and has the version 2.7.16. Somehow ROOT finds the headers in a different location, probably the system ones which have a different version. Make detects the mismatch and stops. Do you build FairSoft with the option build_python? Could you switch off this option?

Ciao

Florian

**Comment by TobiasStockmanns** [comment]
Hi Florian,
thank you for your fast reply. Without python it works. So I have to dig a bit deeper why my python installation is so strange.
I will close the issue.

Ciao,
Tobias
