### ISSUE TITLE
Wrong link to protobuff

### ISSUE THREAD

**Issue by harjke** [FairRootGroup/FairSoft#148]
Hello !
My apologize for that remark,
but could you improve the link to **protobuff**
at /scripts/package_versions.sh ?

The "https://github.com/google/protobuf/releases/download/v3.6.1"
should be replace to https://github.com/protocolbuffers/protobuf/archive/v3.6.0.1.tar.gz.

Thx u!

**Comment by MohammadAlTurany** [comment]
Hello,

If you look carefully what is done here, this is not the link which is used to download the package directly.

in FairSoft/scripts/package_versions.sh

> export PROTOBUF_LOCATION="https://github.com/google/protobuf/releases/download/v3.6.1"
> export PROTOBUF_VERSION=3.6.1

and then in FairSoft/scripts/install_protobuf.sh

> echo "*** Downloading protobuf sources ***"
> download_file $PROTOBUF_LOCATION/protobuf-cpp-$PROTOBUF_VERSION.tar.gz

which translate to:
 download_file [https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz](https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz )

So may be you had a temporary connection problem but this link works.

best,

Mohammad

**Comment by harjke** [comment]
Rly, u absolutely right !
I got it, thanks u.
