### ISSUE TITLE
Missing entry in DYLD_LIBRARY_PATH for OSX

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#149]
When I run FairSoft jun19p1 with FairRoot v18.2.0 and PandaRoot dev I get a runtime error: Loading Geant3 libraries ...
Error in <TMacOSXSystem::FindDynamicLibrary>: libgeant321.so does not exist in /Users/tstockmanns/PandaSoftware/PandaRoot/dev/build/lib:/Users/tstockmanns/PandaSoftware/FairRoot/dev/install/lib:/Users/tstockmanns/PandaSoftware/FairSoft/jun19/build/lib/root:/Users/tstockmanns/PandaSoftware/FairSoft/jun19/build/lib64/Geant3-2.7.0/lib:::.:/Users/tstockmanns/PandaSoftware/FairSoft/jun19/build/lib/root:/usr/local/lib:/usr/X11R6/lib:/usr/lib:/lib:/lib/x86_64-linux-gnu:/usr/local/lib64:/usr/lib64:/lib64:
Loading Geant3 libraries ... finished

Adding /Users/tstockmanns/PandaSoftware/FairSoft/jun19/build/lib to the DYLD_LIBRARY_PATH solves this problem.

**Comment by TobiasStockmanns** [comment]
I see the same problem on Linux with a missing LD_LIBRARY_PATH entry.

**Comment by dennisklein** [comment]
There was an update to the project template which probably needs to be applied in PandaRoot. See FairRootGroup/FairRoot@e3f30cc6ebb73e18a08f1b193b2498cc30665d92. If you create an account for me on your gitlab server, I can offer to test and make a PR.

**Comment by dennisklein** [comment]
@TobiasStockmanns Let's continue the discussion/resolution in https://git.panda.gsi.de/PandaRootGroup/PandaRoot/merge_requests/144.
