### ISSUE TITLE
Removing XRootD in the last release of FairSoft

### ISSUE THREAD

**Issue by kgertsenberger** [FairRootGroup/FairSoft#150]
Good day, all.
We have just moved our experiment software (BmnRoot) from may18p1 FairSoft release to the newest release (jun19p1), but encountered with the following problem:
now FairSoft doesn't include XRootD anymore. We have been using files in ROOT macros located at our remote EOS storage via XRootD (with the "root://" prefix), but now we can't.
Why was XRootD removed from FairSoft and Can you advice how is better to solve it?
Thank you. 
With respect, Konstantin.

**Comment by MohammadAlTurany** [comment]
Hi Konstantin,

We removed the standalone installation of XRootD as we thought nobody use it anymore! sorry for that, I will switch on the ROOT build in XRootD and make a patch release, I think this should cover your use case.
Best,
Mohammad

**Comment by MohammadAlTurany** [comment]
Hi  Konstantin 
I just created a new patch release [jun19p2](https://github.com/FairRootGroup/FairSoft/releases/tag/jun19p2) that contain the Xrootd client in ROOT. 
This should solve your problem. If not please feel free to open this issue again.

**Comment by kgertsenberger** [comment]
Hi.
Sorry for the long answer. Thank you much for the patch.
I will try it. I had errors if I just enable it in rootconfig.sh (jun19p1). I have recently made a patch to correct built-in XRootD compilation.
I'll just try jun19p2 without my patch and write the result.
Thank you for your help.

**Comment by kgertsenberger** [comment]
> Hi Konstantin
> I just created a new patch release [jun19p2]

Dear Mohammad,
I have just checked the last FairSoft jun19p2, it have been compiled successfully but I have remembered that the ROOT with built-in XRootD doesn't copy executable files to the installation directory (it copies only libraries and headers to provide the work of the ROOT libraries concerned with xrootd, e.g. libNetx).
I made the patch to copy also XRootD executable files to _.../install/bin_ directory but I don't know, is it required for FairSoft users. If you want, i can send or attach my patch here.

With respect, Konstantin.

**Comment by MohammadAlTurany** [comment]
Hi Konstantin,

Can you make pull request to the jun19_patches branch?

best,

Mohammad

**Comment by kgertsenberger** [comment]
Yes, of course.
I'll do it in the nearest days.

**Comment by kgertsenberger** [comment]
Dear Mohammad,
i have done it.

**Comment by kgertsenberger** [comment]
Done

**Comment by MohammadAlTurany** [comment]
Thanks!  solved in #154
