### ISSUE TITLE
CI: Define/Add build matrix

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#165]
* [ ] Define build matrix
   * [ ] Write and test singularity container def files for each supported Linux platform
* [ ] Add PR build job
* [ ] Add Nightly build job

**Comment by ChristianTackeGSI** [comment]
Some part of the build matrix stuff is already happening in the form of environment files under `env/`.
We should later revisit this issue and decide, what is needed to resolve it.
