### ISSUE TITLE
To what do I set SIMPATH now?

### ISSUE THREAD

**Issue by rklasen** [FairRootGroup/FairSoft#170]
Hi, the installation with spack went great, thanks for this work. But I don't quite know to what I have to set SIMPATH for FairRoot now. I saw that all packages are compiled to `spack/opt/spack/` and then distribution and compiler dependant sub directories. But no matter to what I set SIMPATH to, FairRoot could never find it.

**Comment by kresan** [comment]
Hi,
You can create a view with spack: I have added a corresponding description to the README.
View is the directory where the links to all packages are put together, exactly what SIMPATH used to be.

**Comment by fuhlig1** [comment]
You can also use the same directory as FAIRROOTPATH since also the complete FairRoot installation is located in the same directory.

**Comment by kresan** [comment]
@rklasen Was the issue with SIMPATH solved using views?
