### ISSUE TITLE
[request] /cvmfs/fairroot.gsi.de: add ROOT python bindings

### ISSUE THREAD

**Issue by klenze** [FairRootGroup/FairSoft#194]
Hi,
I would like to request that the future versions of the binary FairSoft installation provided at /cvmfs/fairroot.gsi.de/ on lxpool.gsi.de and friends are configured with python bindings for ROOT.

Cheers,
   Philipp

**Comment by kresan** [comment]
ROOT from Spack-based FairSoft is now compiled with python bindings (#202 ). Corresponding binaries will be later installed on cvmfs
