### ISSUE TITLE
Compatibility with 2020 FairSoft and FairRoot

### ISSUE THREAD

**Issue by ChristiaanAlwin** [FairRootGroup/FairSoft#195]
ENSARRoot cannot be installed with the current version of FairSoft and FairRoot because it fails to locate the .cmake Geant3 and Geant4 packages. These packages do not exist in FairSoft anymore because they have been replaced with updates. Could the Geant3 and Geant4 interface in ENSARRoot be adapted accordingly?

Yours Sincerely,
dr. C. A. Douma.

**Comment by ChristianTackeGSI** [comment]
Just to clarity: Which exact "2020" version do you mean?

**Comment by ChristiaanAlwin** [comment]
I meant the current version available at GitHub. I myself am currently
working with FairRoot-18.2.1 and FairSoft-jun19p1.

dr. C. A. Douma.

Op ma 24 feb. 2020 om 14:01 schreef Dr. Christian Tacke <
notifications@github.com>:

**Comment by kresan** [comment]
@ChristiaanAlwin Isn't it an issue for ENSARRoot? We can not fix it here.

**Comment by ChristiaanAlwin** [comment]
This message was meant for ENSARRoot. I do not know why you got it as well.
Sorry.

Christiaan Douma.

Op vr 28 feb. 2020 om 09:18 schreef Dmytro Kresan <notifications@github.com
