### ISSUE TITLE
ZeroMQ recipe missing

### ISSUE THREAD

**Issue by karabowi** [FairRootGroup/FairSoft#211]
Dennis removed the `zeromq/package.py` with the commit FairRootGroup/FairSoft@daaf5bf7b038921aef9dd5c22871cc3b3f9f82b2

When I try to install fairroot jun19, I immediately get the error:

```
[jun19] $ spack -C ./config install
==> Error: Package 'zeromq' not found in repository '[Repo 'fairsoft' at '/Users/karabowi/spack/FairSoft']'
[jun19] $ 
```

There is no zeromq in the official list of spack packages:
https://spack.readthedocs.io/en/latest/package_list.html

Shouldn't the zeromq recipe be there in our spack?

**Comment by dennisklein** [comment]
You need to use the spack that is tracked by FairSoft (git submodule inside `spack/`), there the zeromq package exists: https://github.com/FairRootGroup/spack/blob/5c78c771d2f4f78473f5ec9146f4565ef6ee6f39/var/spack/repos/builtin/packages/zeromq/package.py

However, you are right, the current `develop` branch of spack seems to have renamed the `zeromq` package to `libzmq`, see https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/libzmq/package.py

**Comment by dennisklein** [comment]
> You need to use the spack that is tracked by FairSoft (git submodule inside spack/)

Inside your FairSoft clone, run:

```
git submodule update --init
source spack/share/spack/setup-env.sh
```

**Comment by karabowi** [comment]
I've simply followed all the steps listed in the README of the FairSoft dev branch
including the submodule update init:

karabowi@witmac004:~/spack_test/FairSoft$ git submodule update --init
Submodule 'spack' (https://github.com/FairRootGroup/spack.git) registered for path 'spack'
Cloning into '/Users/karabowi/spack_test/FairSoft/spack'...
Submodule path 'spack': checked out '5c78c771d2f4f78473f5ec9146f4565ef6ee6f39'

but still get: 

karabowi@witmac004:~/spack_test/FairSoft$ spack env create jun19_test env/jun19/sim_threads.yaml
==> Created environment 'jun19_test' in /Users/karabowi/spack_test/FairSoft/spack/var/spack/environments/jun19_test
karabowi@witmac004:~/spack_test/FairSoft$ spack env activate jun19_test
[jun19_test] $ spack -C ./config install
==> Error: Package 'zeromq' not found in repository '[Repo 'fairsoft' at '/Users/karabowi/spack_test/FairSoft']'

**Comment by ChristianTackeGSI** [comment]
I miss the
```
$ . ./spack/share/spack/setup-env.sh
```
after the `git submodule update --init`.
Are you 100% sure, that the used spack command the one from FairSoft/spack? Could you try `spack location -r` please?

**Comment by karabowi** [comment]
Hi, 

I can copy all of the commands and the output:

Last login: Fri Apr  3 10:40:22 on ttys011
karabowi@witmac004:~$ mkdir spack_test
karabowi@witmac004:~$ cd spack_test/
karabowi@witmac004:~/spack_test$ git clone -b dev https://github.com/FairRootGroup/FairSoft
Cloning into 'FairSoft'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 3400 (delta 23), reused 38 (delta 12), pack-reused 3340
Receiving objects: 100% (3400/3400), 18.29 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (2120/2120), done.
karabowi@witmac004:~/spack_test$ cd FairSoft/
karabowi@witmac004:~/spack_test/FairSoft$ git submodule update --init
Submodule 'spack' (https://github.com/FairRootGroup/spack.git) registered for path 'spack'
Cloning into '/Users/karabowi/spack_test/FairSoft/spack'...
Submodule path 'spack': checked out '5c78c771d2f4f78473f5ec9146f4565ef6ee6f39'
karabowi@witmac004:~/spack_test/FairSoft$ source spack/share/spack/setup-env.sh
karabowi@witmac004:~/spack_test/FairSoft$ spack -C ./config bootstrap
==> Requirement environment-modules is satisfied with installed package environment-modules@4.3.1%clang@10.0.1-apple~X arch=darwin-mojave-x86_64 ^tcl@8.6.8%clang@10.0.1-apple arch=darwin-mojave-x86_64 ^zlib@1.2.11%clang@10.0.1-apple+optimize+pic+shared arch=darwin-mojave-x86_64
karabowi@witmac004:~/spack_test/FairSoft$ spack repo add .
==> Added repo with namespace 'fairsoft'.
karabowi@witmac004:~/spack_test/FairSoft$ spack env create jun19_test env/jun19/sim_threads.yaml
==> Created environment 'jun19_test' in /Users/karabowi/spack_test/FairSoft/spack/var/spack/environments/jun19_test
karabowi@witmac004:~/spack_test/FairSoft$ spack env activate jun19_test
[jun19_test] $ spack -C ./config install
==> Error: Package 'zeromq' not found in repository '[Repo 'fairsoft' at '/Users/karabowi/spack_test/FairSoft']'
[jun19_test] $ spack location -r
/Users/karabowi/spack_test/FairSoft/spack
[jun19_test] $ spack --version
0.13.2
[jun19_test] $ 

yours,
Radek

**Comment by ChristianTackeGSI** [comment]
Okay, there are two things, that come to my mind:
1. Could you try a `spack repo list` to see, if the `FairSoft/spack/var/spack/repos/buildin` directory is included? (which hopefully has the zeromq in it?)
2. A left over, broken `~/.spack`. Could you try removing it?

**Comment by MohammadAlTurany** [comment]
I had a similar problem which was finally related to the fact that Spack can add multiple repositories with the same name but then it will take the first one in the list (I had two FairSoft pointing to different directories). You should see if this is the case with _**spack repo list**_.

**Comment by karabowi** [comment]
@ChristianTackeGSI : 
1. the directory you mentioned was included, but
2. I've deleted almost everything from ~/.spack and then spack installs everything
without any problem.
Thanks for the tip.
@MohammadAlTurany : 
I think that this advice could also work - I wanted to start a new spack besides my old to see how it's working from scratch. I was hoping that having them in separate directories would be enough.
Apparently not...
