### ISSUE TITLE
Geant4 bug in version 10.4 and newer

### ISSUE THREAD

**Issue by fuhlig1** [FairRootGroup/FairSoft#213]
Recently a bug was found in  GEANT4 versions 10.4 and newer.
GEANT4 developers proposed the following quick fix:

https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2226#c8

Some tests with CBMROOT were made (we have GEANT4 10.5.1 in the latest FairSoft release) 
which confirmed that CBM is affected by the bug. (see https://redmine.cbm.gsi.de/issues/1647)

A fix was applied on the CBMROOT level when initializing Geant4 but it would be much better to fix the issue in FairSoft if the new version of Geant4 is still affected.

**Comment by fuhlig1** [comment]
I rechecked the Geant4 bug report and there it is clearly stated that the problem will be fixed in versions > 10.6, so we are affected by the bug. Since the bugfix is a one line correction in one of the source files I would propose to add a patch to our recipe and fix the bug as described in the bug report.

**Comment by ChristianTackeGSI** [comment]
The patch has been merged. If you have a chance, please test and confirm, that this fixes your issues.
