### ISSUE TITLE
Concretizer fails without hints

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#234]
In some cases the concretizer is not able to find the solution that is obvious to the user.

* Upstream issues: ?
* Current workaround: Added additional root specs to the environment
   * `pcre+jit`

**Comment by dennisklein** [comment]
No longer needed with Spack 0.14.2, see #284

**Comment by ChristianTacke** [comment]
In some sense, the python pinning can be counted as a concretizer hint also. Really, we'd just like to say `python@:2.99`, but that didn't work last time. No idea, if it's still needed. I'll try soon.
