### ISSUE TITLE
Support FairSoft compilation with C++14

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#236]
Use case: see FairRootGroup/FairRoot#961 (FairRoot + [PCL](https://github.com/PointCloudLibrary/pcl) 1.10 + ROOT dictionaries)

We should probably create a FAQ entry on how to achieve this with Spack.

**Comment by ChristianTackeGSI** [comment]
I see two major points here:

1. Tell people about `packages.yaml` and setting a global variant `cxxstd=14` there for all packages.
2. If building package a with `cxxstd=X` means that package B _must_ be compiled with the same `cxxstd`, then we must fix that in the `depends_on`.

About (2), I have seen something like
```python
for v in ('11', '14'):
    depends_on('dep cxxstd={0}.format(v), when='cxxstd={0}'.format(v))
```
That doesn't mean I want to promote this, but just as a "if it's needed, one can do this".

**Comment by dennisklein** [comment]
About (2): For pure dynamic link dependencies, one can mix and match libraries compiled with different cxx language levels in general (as long as it is the same compiler version). There are a few edge cases when this is not true with some sensitive macro code in headers. But then there is the root interpreter... From the PCL use case it appears to me that we need to keep all packages on the same cxx language level that have root dictionaries and get loaded into the same root session together.

**Comment by dennisklein** [comment]
Or maybe it is a bit weaker, maybe just root needs to be compiled with a cxx language level higher or equal to the highest packages with root dictionaries?

**Comment by ChristianTackeGSI** [comment]
spack's depends_on doesn't allow us something like `cxxstd>={0}`.

So this sounds like every dictionary providing package should have the above mentioned loop on its `depends_on('root')`?

**Comment by dennisklein** [comment]
> So this sounds like every dictionary providing package should have the above mentioned loop on its `depends_on('root')`?

Yes, that is my guess, too.

**Comment by dennisklein** [comment]
Note: The legacy `nov20` release supports and defaults to C++14

**Comment by ChristianTackeGSI** [comment]
Just to add to the "note"-list:
* dds 3.5.4 requires `cxxstd=default` or `cxxstd=17`, see: https://github.com/FairRootGroup/FairSoft/pull/355#issuecomment-750288944
* I think, root 6.20 doesn't work with cxxstd=17 on some machines. We possibly should document that in the spack recipe somehow?

**Comment by dennisklein** [comment]
> > So this sounds like every dictionary providing package should have the above mentioned loop on its `depends_on('root')`?
> 
> Yes, that is my guess, too.

Did we gain any further insight on this matter? Looks like this is the last open point of this issue.

**Comment by ChristianTackeGSI** [comment]
I don't think, we really got further with this thing.

Do we know which packages have specific dependency requirements that would need the cxxstd-pinning?

Looking over it, I see another open point:
* Add a FAQ to tell people to use `packages.yaml` to set a global `cxxstd=17`, if they need that for whatever reason?

**Comment by ChristianTackeGSI** [comment]
See #385 for some movement in the spack world.

Also legacy nov20 already shipped as cxxstd=14.

Next legacy will be cxxstd=17.

**Comment by dennisklein** [comment]
Both `nov20` and `apr21` are shipped with cxxstd=14 and 17 respectively in both legacy and spack. Closing as solved.
