### ISSUE TITLE
flatbuffers version info missing

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#241]
On Fedora31 with `env/dev/sim_no-threads.yaml` (ad677d9ac4c78324a9f152a57a69de31cf9d32b4) the installed `lib64/cmake/flatbuffers/FlatbuffersConfigVersion.cmake` contains

```cmake
set(PACKAGE_VERSION "..")
```

**Comment by ChristianTackeGSI** [comment]
`include/flatbuffers/base.h` in the install-tree has the correct version in it.

That said, the cmake code uses git to detect its own version. And I guess, it fails on the "release tarballs".

Is this blocking the release?

**Comment by dennisklein** [comment]
Not blocking blocking. We print a table during build which reports this wrong version.

**Comment by dennisklein** [comment]
fixed in `dev`

**Comment by ChristianTackeGSI** [comment]
We still need to adress that upstream.
https://github.com/FairRootGroup/FairSoft/projects/1#card-43858756

**Comment by dennisklein** [comment]
It will be solved by #182 without the need to modify the upstream package.

**Comment by ChristianTackeGSI** [comment]
Well, either flatbuffers upstream, or spack upstream (git caching and/or flatbuffers recipe). In one of both places, we need to do something.

**Comment by ChristianTackeGSI** [comment]
Okay, for the record, I have filed a bug with flatbuffers:
https://github.com/google/flatbuffers/issues/6074

Let's see, if they fix that.
