### ISSUE TITLE
FairSoft installation of Jul15 fails on openSUSE 13.1

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#27]
In the installation of the external packages I get an error about a missing header file: gssapi/gssapi_generic.h
On OSX it works.

The complete error message is here:
Making all in src
make[1]: Entering directory `/private/fairsoft/jul15/basics/zeromq-4.1.0/src'
make  all-am
make[2]: Entering directory `/private/fairsoft/jul15/basics/zeromq-4.1.0/src'
  CXX    libzmq_la-gssapi_mechanism_base.lo
In file included from gssapi_mechanism_base.cpp:34:0:
gssapi_mechanism_base.hpp:28:35: fatal error: gssapi/gssapi_generic.h: No such file or directory
 #include <gssapi/gssapi_generic.h>
                                   ^
compilation terminated.
make[2]: *** [libzmq_la-gssapi_mechanism_base.lo] Error 1
make[2]: Leaving directory `/private/fairsoft/jul15/basics/zeromq-4.1.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/private/fairsoft/jul15/basics/zeromq-4.1.0/src'
make: *** [all-recursive] Error 1
Making install in src
make[1]: Entering directory `/private/fairsoft/jul15/basics/zeromq-4.1.0/src'
  CXX    libzmq_la-gssapi_mechanism_base.lo
In file included from gssapi_mechanism_base.cpp:34:0:
gssapi_mechanism_base.hpp:28:35: fatal error: gssapi/gssapi_generic.h: No such file or directory
 #include <gssapi/gssapi_generic.h>
                                   ^
compilation terminated.
make[1]: *** [libzmq_la-gssapi_mechanism_base.lo] Error 1
make[1]: Leaving directory `/private/fairsoft/jul15/basics/zeromq-4.1.0/src'
make: *** [install-recursive] Error 1
**** Checking libraries in /private/fairsoft/jul15_build/lib ****
*** ERROR: zeromq could not be created.
*** End installation of external packages with Errors***

**Comment by fuhlig1** [comment]
Hi Tobias,

can you please try to install the following package

krb5-devel

and then try again to compile zeromq.

Ciao

Florian

Am 13.10.2015 um 13:40 schrieb Tobias Stockmanns <notifications@github.com>:
