### ISSUE TITLE
Add fairsoft-config package

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#271]
which provides a `fairsoft-config` script and add it to the existing environments

**Comment by ChristianTackeGSI** [comment]
It would probably depend on fairoot? Or on the dependencies of fairroot?

If it depends on fairroot, then we might consider just adding the script to fairroot?

**Comment by dennisklein** [comment]
> It would probably depend on fairoot? Or on the dependencies of fairroot?
> 
> If it depends on fairroot, then we might consider just adding the script to fairroot?

I would not add any dependency from this package, just a simple small package we add to all environments where the fairsoft-config script is needed still.

I could also be convinced to have the fairroot pkg depend on it to automatically pull it into all context where it is needed.

**Comment by dennisklein** [comment]
The bigger question to me is, do we care whether the output of the `fairsoft-config` script is true or not.

**Comment by dennisklein** [comment]
```
# /cvmfs/fairroot.gsi.de/fairsoft/jun19p1/bin/fairsoft-config
Usage: fairsoft-config [--version] [--cc] [--cxx] [--f77]  [--cxxflags] [--root-version] [--help]
# /cvmfs/fairroot.gsi.de/fairsoft/jun19p1/bin/fairsoft-config --version
jun19
# /cvmfs/fairroot.gsi.de/fairsoft/jun19p1/bin/fairsoft-config --root-version
6
# /cvmfs/fairroot.gsi.de/fairsoft/jun19p1/bin/fairsoft-config --cc
/usr/bin/gcc
# /cvmfs/fairroot.gsi.de/fairsoft/jun19p1/bin/fairsoft-config --cxx
/usr/bin/g++
# /cvmfs/fairroot.gsi.de/fairsoft/jun19p1/bin/fairsoft-config --f77
/usr/bin/gfortran
# /cvmfs/fairroot.gsi.de/fairsoft/jun19p1/bin/fairsoft-config --cxxflags
-std=c++11
```

**Comment by dennisklein** [comment]
`--version` we can model with a package version and the environment needs to choose the right one.

`--root-version` will be fine to hardcode to `6`.

`--cc`, `-cxx`, `-f77` should be queryable in the recipe I hope.

`--cxxflags` is the hard part. A single package cannot really enforce or query this in spack. I'll probably just hardcode it to `-std=c++11` or `14` even though it is not true - currently we have a mixture.

**Comment by ChristianTackeGSI** [comment]
> `--version` we can model with a package version and the environment needs to choose the right one.

Sounds good.

> `--root-version` will be fine to hardcode to `6`.

Or `self.spec['root'].version.up_to(1)` (or something like that) ;)

> `--cc`, `-cxx`, `-f77` should be queryable in the recipe I hope.

Yes, there are:
* some global variables `spack_cc`, `spacl_cxx`, `spack_fc`, `spack_f77`.
  But I guess, they point to some wrappers. I don't know, if they work properly outside of spack. Or if they depend on magic environment variables, that only spack sets…
* an object: `self.compiler`, which for example has the following attributes: `.name`, `.fc`, `.f77`, `.cc`, `.cxx`, `.cc_pic_flag`, `.cc_rpath_arg` (that's the common ones I have found being used in package recipes)
  `lib/spack/spack/compilers/gcc.py` has the implementation of `self.compiler`.

> `--cxxflags` is the hard part. A single package cannot really enforce or query this in spack. I'll probably just hardcode it to `-std=c++11` or `14` even though it is not true - currently we have a mixture. Well, I guess I'll make it settable with a variant.

Give it a standard cxxstd flag? When we get to this cxxstd stuff, we'll let fairsoft-config depend on for example `root cxxstd={same version}` or somesuch.
Or we tell people to set the default cxxstd in `packages.yaml` as a default variant. Let's see later.
