### ISSUE TITLE
Experiences Compiling FairSoft (w/ ROOT 5) on OS X El Capitan

### ISSUE THREAD

**Issue by AndiH** [FairRootGroup/FairSoft#28]
Having no timely-pressing task at hand involving *ROOT, I decided to upgrade my OS X to the latest El Capitan version.

Here are some notes on installing FairSoft dev there.

* **OpenSSL**: As @fuhlig1 in commit f98b5dc (dev) mentioned, Apple decided [OpenSSL to be not stable enough](http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html) for their product and discontinued including OpenSSL headers. Unfortunately, f98b5dc did not work for me – for me the proper `OPENSSL_ROOT_DIR` is `/usr/local/opt/openssl/`, which is also mentioned in the official `brew info openssl` part. So, in short, adding `/opt/openssl/` to Florian's commit fixes this problem.
* **boost**: As usual, when downloading boost, you end up with the Sourceforge webpage piped into a file called `boost_1_58_0.tar.bz2`. The following command extracts the url from the file: `grep refresh boost_1_58_0.tar.bz2 | egrep -o 'https?://[^ ">]+' ` which can then be downloaded with the browser. Sometimes, it worked to pipe the output of this to `wget` (via `xargs`) with the additional `--content-disposition ` option, but this was not reliable. This Sourceforge download *bug* is a major point of annoyance; it's **the** error I'm solving most of the times here in our institute when others are installing FairSoft.
* **xcode-select**: I got the error `Error: cannot open file "AvailabilityMacros.h"  in .../core/base/inc/RConfig.h:384`. This being a fresh upgrade I seem to need to rerun `xcode-select --install`… Got the hint, among other locations, from [here](https://github.com/Homebrew/homebrew-science/issues/1269).

By the way: There's a new ROOT version (5.34/34, Oct 2) [claiming to fix a RPATH treatment of El Capitan](https://root.cern.ch/root-version-v5-34-00-patch-release-notes). My guess it has something to do with the last of my errors, but when using 5.34/34, I wasn't able to compile Pluto any longer (although I might also have done something else wrong, I'm not entirely sure).

Do you want me to try ROOT 6 as well?

**Comment by TobiasStockmanns** [comment]
Here are my experiences up to now.

I had to update my xcode to xcode7 manually.
I had the same OpenSSL problem Andreas pointed out.
In addition the installation of Geant4 does not work becuase X11 Xmu library is not found:

*** Compiling Geant4-build ................ 
-- The C compiler identification is AppleClang 7.0.0.7000176
-- The CXX compiler identification is AppleClang 7.0.0.7000176
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Clang version : 7.0.0
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found EXPAT: /usr/lib/libexpat.dylib (found version "2.0.1") 
-- Found XercesC: /Users/Stockmanns/PandaSoftware/FairSoft/dev_build/lib64/libxerces-c.dylib  
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /opt/X11/lib/libX11.dylib
CMake Error at cmake/Modules/Geant4InterfaceOptions.cmake:220 (message):
  could not find X11 Xmu library and/or headers
Call Stack (most recent call first):
  CMakeLists.txt:106 (include)

-- Configuring incomplete, errors occurred!

**Comment by TobiasStockmanns** [comment]
Reinstalling XQuartz solved the problem.

**Comment by TobiasStockmanns** [comment]
The installation of ROOT crashes because the netx package cannot find the include directory of proofd (see attached compiler output). I could fix this by manually adding the directory into the CMakeLists.txt file of netx. 

/Users/Stockmanns/PandaSoftware/FairSoft/dev/tools/root/net/netx/src/TXNetFile.cxx:64:10: fatal error: 
      'XpdSysPthread.h' file not found
#include "XpdSysPthread.h"
         ^
/Users/Stockmanns/PandaSoftware/FairSoft/dev/tools/root/net/netx/src/TXNetSystem.cxx:42:10: fatal error: 
      'XrdProofdXrdVers.h' file not found
#include "XrdProofdXrdVers.h"
         ^
1 error generated.
make[2]: *** [net/netx/CMakeFiles/Netx.dir/src/TXNetSystem.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [net/netx/CMakeFiles/Netx.dir/src/TXNetFile.cxx.o] Error 1
make[1]: *** [net/netx/CMakeFiles/Netx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by DanielWielanek** [comment]
I have the same problem:  "'XrdProofdXrdVers.h' file not found"  on Linux-Mint. Usually I just copy all headers from FairSoft/tools/root/proof/proofd/inc to into FairSoft/tools/root/build_for_fair/include/root. Maybe this should be just added to script that install ROOT files?

**Comment by fuhlig1** [comment]
Following the instructions at https://fairroot.gsi.de/?q=node/106 I could install FairSoft without problems. This holds for ROOT5 and ROOT6. Actually this was tested 2 or 3 month ago. I am not sure if it would still work if there is a new XCode version.
