### ISSUE TITLE
Geatn4 Cmake error with FairSoft on OSX Yosemite

### ISSUE THREAD

**Issue by mckunkel** [FairRootGroup/FairSoft#29]
Greetings, 

I am attempting to install FairSoft on Mac OSX 10.10.5 Xcode 7.1.

The Geant4 part of the build is failing.

CMake Error at cmake/Modules/Geant4MacroUtilities.cmake:125 (message):
  Value 'c++11' for variable GEANT4_BUILD_CXXSTD is not allowed

  It must be selected from the set: c++98 (DEFAULT: c++98)

**Comment by MohammadAlTurany** [comment]
Hallo,
Do you use the Master branch of FairSoft? if yes please try with the dev branch, it should work!
best,
Mohammad

**Comment by mckunkel** [comment]
Thank you, the dev version worked.
