### ISSUE TITLE
intel-tbb

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#299]
Installation of FairSoft via spack fails with the following error:
```
spack install
==> Warning: apple-clang@11.0.3 cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
==> Error: Package 'intel-tbb' not found.
```

This error happens with all tested environments: dev/sim/ jun19/sim /env/dev/fairroot_develop

**Comment by dennisklein** [comment]
This is most likely an artifact from a previous build, pls try `spack clean -ms` and then re-create the environment.

(We have already added this step to the new [`thisfairsoft.sh` env script](https://github.com/FairRootGroup/FairSoft/pull/298/commits/4c23a7896720ed107521b1302a222ec8d556d323), it will land in `dev` this week but is already available in `dev_new_spack` - the latter branch also has some gfortran10-related fixes.)

**Comment by TobiasStockmanns** [comment]
Running spack clean -ms solves the itel-tbb issue.
