### ISSUE TITLE
thisfairsoft.sh does not work for zsh shell

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#313]
Running `source thisfairsoft.sh --setup` results in a crash of the script with the following error message:
`thisfairsoft.sh:7: = not found`

Fix would be to replace `if [ "$1" == "--setup" ]` with `if [ "$1" = "--setup" ]`.

The usage of `==` is not POSIX conform.

**Comment by ChristianTackeGSI** [comment]
Fix is in #314. 

Just out of curiosity: Which shell are you using? The main supported shell is bash. zsh might also work.

**Comment by TobiasStockmanns** [comment]
I am using the zsh shell within iTerm2 on OSX.
