### ISSUE TITLE
Reduce size of FairSoft dependency tree to the order it was in legacy FairSoft

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#316]
Investigate at least two possibilities:
* `packages.yaml`
* drop `depends_on` statements

**Comment by ChristianTackeGSI** [comment]
Removed the milestone for now. I doubt we're going to handle the spack edition for this release. And the new legacy handles all of this for now.

**Comment by dennisklein** [comment]
Closing, it is unlikely we will have good universal system integration with spack without significant development effort for all platforms. Spack appears to have chosen against an integration with the native system package managers and uses its own discovery method](https://spack.readthedocs.io/en/latest/build_settings.html?#automatically-find-external-packages).
