### ISSUE TITLE
pythia8 installation fails with latest dev version

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#326]
Dear developers,

I am on the following dev version of FairSoft (latest version 24.9.2020) 995dafd399172ec168150b5f5c8a8c45e16f70de
on an OSX 10.15.6.

During the installation process I get the following error:
```
==> Installing pythia8
==> No binary for pythia8 found: installing from source
==> Error: Failed to install pythia8 due to AttributeError: Can't pickle local object 'fork.<locals>.child_process'
==> Error: Can't pickle local object 'fork.<locals>.child_process'
```

**Comment by dennisklein** [comment]
This looks like the known error that Spack 0.15 does not work with Python 3.8 on macOS. It appears there is a fix now in their dev branch (https://github.com/spack/spack/pull/18124) though. We wilp have a look if a backport is feasible. As a workaround you may use Python < 3.8.

**Comment by ChristianTackeGSI** [comment]
Looking into a backport just now.

**Comment by ChristianTackeGSI** [comment]
Fix is hopefully in #327 
Let's wait for the CI
Our CI still has Python 3.7 on the macs. We might upgrade one of them (likely the newer one).

**Comment by dennisklein** [comment]
I just merged it into `dev`. I'll update python on one of our CI macs.

**Comment by TobiasStockmanns** [comment]
For me the update worked and I can install FairSoft now.

**Comment by ChristianTackeGSI** [comment]
> For me the update worked and I can install FairSoft now.

Okay. I am closing this now.

If there is anything we missed, please re-open / ping us to re-open!
