### ISSUE TITLE
Reversed patch detected

### ISSUE THREAD

**Issue by Barthelemy** [FairRootGroup/FairSoft#33]
Hello, 

When using the recoonly config I got the following : 

```
patching file cmake/modules/SearchInstalledSoftware.cmake
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file cmake/modules/SearchInstalledSoftware.cmake.rej
```

It is on SLC6 using ROOT 6. 

First of all, it seems to be an error that needs to be fixed. 
The second thing is that the script should handle automatically this case because it blocks everything at the moment.

**Comment by MohammadAlTurany** [comment]
As we are moving to the new build system (AliBuild) I will close this issue.
