### ISSUE TITLE
Installing FairSoft on Ubuntu 20

### ISSUE THREAD

**Issue by JanaRieger** [FairRootGroup/FairSoft#339]
When I try installing FairSoft on my laptop with Ubuntu 20, I get the following error message while running configure.sh:

```
make: *** [Makefile:152: all] Error 2
**** Checking libraries in /home/jana/fairsoft_jun19/build/lib ****
*** ERROR: root could not be created.
 create a symbolic linking for  Vc library ....
scripts/install_root6.sh: line 69: cd: /home/jana/fairsoft_jun19/build/lib/root: No such file or directory
ln: failed to create symbolic link './libVc.a': File exists
---link created ---
*** End installation of external packages with Errors***
```

What could be the reason for this?

**Comment by dennisklein** [comment]
For further assistance, please attach the generated `*.log` files here.

**Comment by JanaRieger** [comment]
[Install_161020_085943.log](https://github.com/FairRootGroup/FairSoft/files/5414843/Install_161020_085943.log)

**Comment by JanaRieger** [comment]
[libraries_161020_085943.log](https://github.com/FairRootGroup/FairSoft/files/5414862/libraries_161020_085943.log)

**Comment by dennisklein** [comment]
What is the output of `git describe` when executed inside your git clone directory of FairSoft?

**Comment by JanaRieger** [comment]
jun19p1-1-gfa300fb

**Comment by karabowi** [comment]
I have just tried to install jun19 on Ubunt20 and have observed similar problem caused by failed XROOTD installation.
I have removed the XROOTD builtin installation option from tools/rootconfig.sh
and with this change the installation of FairSoft went smooth:

```
diff --git a/tools/rootconfig.sh b/tools/rootconfig.sh
-                    -Dminuit2=ON  -Dgdml=ON -Dxml=ON -Dbuiltin_xrootd=ON \
+                    -Dminuit2=ON  -Dgdml=ON -Dxml=ON \
```

Try if it works as a temporary solution.

**Comment by JanaRieger** [comment]
Thank you, that worked!
