### ISSUE TITLE
Install also ODC for release nov20

### ISSUE THREAD

**Issue by fuhlig1** [FairRootGroup/FairSoft#344]
Since some projects already use ODC or want to use it in near future it would be good if ODC is installed with all the other FairSoft packages. The installation would reduce the work for users.

**Comment by dennisklein** [comment]
@AndreyLebedev Which version of ODC should we best include in the `nov20` release of FairSoft? Do you have any comments, remarks regarding the compile config and/or needed dependencies?

**Comment by AndreyLebedev** [comment]
@dennisklein The latest version is 0.10 is the one which supports multiple partitions (DDS sessions). I would recommend using it. But it requires the latest DDS (3.5.3) and the latest FairMQ (1.4.26) versions. If this is not an issue then please use the latest.

**Comment by ChristianTackeGSI** [comment]
For FairSoft spack edition, see #345. Some questions still open, see there.

**Comment by dennisklein** [comment]
Implemented.
