### ISSUE TITLE
root 6.20 misses TSpectrum

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#348]
In root 6.20 the class `TSpectrum` is optional and the build process has to be enabled via the cmake option `-Dspectrum={OFF,ON}`.

In PandaRoot `TSpectrum` is needed. Therefore the request is to enable it in the building of root.

---

EDIT by Christian Tacke to include the checklist here:

- [x] spack edition: #349
- [x] legacy edition: #350
- [X] spack upstream: https://github.com/spack/spack/pull/19971

**Comment by ChristianTackeGSI** [comment]
I'll take care for the spack edition now.

If Dennis isn't quicker, I'll look into legacy after that.

**Comment by ChristianTackeGSI** [comment]
Should be fixed.
Please complain, if things are wrong.
