### ISSUE TITLE
[legacy] nov20 build fails on macOS 11

### ISSUE THREAD

**Issue by kresan** [FairRootGroup/FairSoft#363]
Build of ROOT fails with the following error message:

```
-- Looking for GLEW
-- Found GLEW: /usr/local/lib/cmake/glew/glew-config.cmake  
CMake Error at cmake/modules/SearchInstalledSoftware.cmake:524 (message):
  Please enable builtin Glew due bug in latest CMake (use cmake option
  -Dbuiltin_glew=ON).
```

Using cmake version: 3.19.2

**Comment by dennisklein** [comment]
A fix used in the root vcpkg has been adapted and integrated in the `nov20_patches` branch (75548afaa0050b7da3b36ebcef985242b633d966) and will be included in the next patch release.
