### ISSUE TITLE
[legacy] Legacy installation of Nov20 misses gsl

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#364]
In the legacy build of Nov20 the GNU Scientific Library (gsl) is missing. Therefore root::math::MathMore is not generated which is needed in PandaRoot.

**Comment by ChristianTackeGSI** [comment]
I wonder, whether we want to
* add `-Dmathmore=ON` (which is the default) to document PandaRoot's need explicitly.
* add `+math` (which is the default currently) to the spack edition to document PandaRoot's need there as well.
* add `-Dfail-on-missing=ON` so that root's cmake fails early, if things don't match up. (spack has this already.)

**Comment by karabowi** [comment]
I think that adding a flag will not work. We have to add GSL to the list of prerequisites or install it together with legacy.

**Comment by ChristianTackeGSI** [comment]
> I think that adding a flag will not work. We have to add GSL to the list of prerequisites or install it together with legacy.

ACK!

My flag ideas are meant *in addition*.

We have three options (in order of my preference, first being preferred):
1. Add it to the requirements. If we can get it everywhere, I'd vote for that!
   * Debian has `libgsl-dev` which I use in our escape / spack container
   * brew seems to have [this](https://formulae.brew.sh/formula/gsl)
   * Fedora surely has it.
   * opensuse: TBD
2. Adding `-Dbuiltin_gsl=ON` to the ROOT flags
3. Compiling it along with legacy.

**Comment by dennisklein** [comment]
@TobiasStockmanns @karabowi What happens if you install the packages we recommend as system prerequisites: https://github.com/FairRootGroup/FairSoft/blob/nov20/legacy/setup-macos.sh? (Leave out `xrootd` since there is a separate issue with it at the moment: #367)

**Comment by ChristianTackeGSI** [comment]
Ping: @TobiasStockmanns @karabowi 

How should we go on with this?

**Comment by dennisklein** [comment]
> Ping: @TobiasStockmanns @karabowi
> 
> How should we go on with this?

@TobiasStockmanns commented in last meeting that it was likely that he did not have the gsl brew package installed. So it was not really missing, it was just overlooked that we moved it to the system prerequisites.

However, we will add the `-Dmathmore=ON` flag as you proposed and make sure all our `setup-*.sh` scripts list the gsl package. I am on it.
