### ISSUE TITLE
[legacy] [nov20] ROOT 6.20.08 build fails on macOS 11.1

### ISSUE THREAD

**Issue by kresan** [FairRootGroup/FairSoft#367]
**Error message:**
```
[ 60%] Building CXX object proof/proofd/CMakeFiles/XrdProofd.dir/src/XrdProofConn.cxx.o
In file included from /Users/kresan/SSD2/FairSoft/nov20/build/Source/root/proof/proofd/src/XrdProofConn.cxx:34:
/Users/kresan/SSD2/FairSoft/nov20/build/Source/root/proof/proofd/inc/XrdProofConn.h:140:4: error: unknown type name 'XReqErrorType'; did you mean 'XProtocol::XReqErrorType'?
   XReqErrorType       LowWrite(XPClientRequest *, const void *, int);
   ^~~~~~~~~~~~~
   XProtocol::XReqErrorType
/usr/local/include/xrootd/XProtocol/XProtocol.hh:1343:6: note: 'XProtocol::XReqErrorType' declared here
enum XReqErrorType {
     ^
```

```
$ brew config
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 402261623f80d0e7b038993e5baf68ff4d9b6d73
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
```

```
$ brew info xrootd
xrootd: stable 5.0.3 (bottled), HEAD
High performance, scalable, fault-tolerant access to data
https://xrootd.slac.stanford.edu/
/usr/local/Cellar/xrootd/5.0.3 (290 files, 9.4MB) *
  Poured from bottle on 2021-01-07 at 09:06:12
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/xrootd.rb
License: LGPL-3.0-or-later
==> Dependencies
Build: cmake ✔
Required: openssl@1.1 ✔, readline ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 1,131 (30 days), 2,930 (90 days), 8,890 (365 days)
install-on-request: 244 (30 days), 558 (90 days), 1,329 (365 days)
build-error: 0 (30 days)
```

**Comment by kresan** [comment]
@karabowi can you post ```brew info xrootd``` here?

**Comment by karabowi** [comment]
My xrootd is one version older:

karabowi@witmac004:~$ brew info xrootd
xrootd: stable 4.12.5 (bottled), HEAD
High performance, scalable, fault-tolerant access to data
https://xrootd.slac.stanford.edu/
/usr/local/Cellar/xrootd/4.12.5 (308 files, 7.8MB) *
  Poured from bottle on 2020-11-05 at 12:41:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/xrootd.rb
License: LGPL-3.0-or-later
==> Dependencies
Build: cmake ✘
Required: openssl@1.1 ✔, readline ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 1,131 (30 days), 2,930 (90 days), 8,890 (365 days)
install-on-request: 244 (30 days), 558 (90 days), 1,329 (365 days)
build-error: 0 (30 days)

**Comment by kresan** [comment]
As I expected. ROOT 6.20.08 does not work with xrootd 5.0.3.

**Comment by kresan** [comment]
@dennisklein What was the reason to have -Dxrootd=ON? As far as I know we need only client support, so it is enough to have -Dbuiltin_xrootd=ON

**Comment by ChristianTackeGSI** [comment]
* `-Dxrootd` is there, because we have `+xrootd` in the spack world.
  I don't remember exactly, why we have it.
* Yes, spack recipes confirm, that only < 5.0 is supported. Do newer ROOT versions support 5.x?
* `-Dbuiltin_xrootd=ON` does only download full xrootd and compile it inside root. Having a system xrootd (library) is usually the better option, and especially the space saving option.

Can we get xrootd 4.x from brew? I am starting to doubt it… Can someone with more brew knowledge confirm?

If we can't get xrootd 4.x from brew, yes, we have to either compile it as an external packege ourselves, or use `-Dbuiltin_xrootd=ON`.

**Comment by dennisklein** [comment]
Can you also verify that the builtin xrootd compiles before we change it? If I remember correctly it was not building on some platforms. Maybe there is no one fits all flag.

**Comment by dennisklein** [comment]
Isn't root switching to the builtin xrootd automatically? Just do `brew uninstall xrootd`?

**Comment by ChristianTackeGSI** [comment]
Nope, if xrootd isn't found, and `builtin_xrootd` isn't set, then xrootd support is completely disabled.
See: https://github.com/root-project/root/blob/v6-20-00-patches/cmake/modules/SearchInstalledSoftware.cmake#L849-L862

**Comment by ChristianTackeGSI** [comment]
I considered doing some `find_package(XROOTD)` in `cmake/legacy.cmake`, but we will only get `XROOTD_FOUND`, but not the version.

See: #365 for the builtin_xrootd-variant.

**Comment by dennisklein** [comment]
The needed XRootD 5 support patches (db9ca700789f0667e460e00e74940961db1009d1) have been backported to the `nov20_patches` branch and will be included in the next patch release.
