### ISSUE TITLE
homebrew package: Replace `depends_on :x11`

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#369]
It looks like X11 is now properly packaged in homebrew. As a consequence dependency on xquartz via cask is deprecated:

```
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
```

See https://github.com/Homebrew/homebrew-core/pull/57995.

**Comment by dennisklein** [comment]
See https://github.com/Homebrew/homebrew-core/pull/64308#issuecomment-724358627 for opengl

**Comment by dennisklein** [comment]
A first test by @fuhlig1 shows that we could replace the `depends_on :x11` with
```
depends_on 'mesa-glu'
depends_on 'libxft'
depends_on 'libxpm'
```
We should still verify this on at least another system.

**Comment by dennisklein** [comment]
See #371 on how to teach Geant4 to find the mesa-gl packages from brew.

**Comment by fuhlig1** [comment]
Agreed. The patch was excepted by the Geant4 developers already and will probably be in the next upstream release.

**Comment by dennisklein** [comment]
change of plans, brew disabled `:x11` already...

**Comment by dennisklein** [comment]
the homebrew package `fairsoft@21.4` no longer depends on `:x11`. So, `fairsoft@20.11` is a WONTFIX.
