### ISSUE TITLE
Geane error in nov20 release

### ISSUE THREAD

**Issue by karabowi** [FairRootGroup/FairSoft#372]
When doing propagation with Geane, there are lots of errors in ERTRAK 
and occasionally a segmentation violation.
The ERTRAK errors are not themselves crashing the reconstruction,
but on the other hand the tracks are not propagated at all.
The output looks like this:

   Error in ERTRAK : Inconsistent character options. Tracking stops now

    Error in ERTRAK : Inconsistent character options. Tracking stops now

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
Root > root.exe(4111,0x10c9d15c0) malloc: *** error for object 0x7fc2bbff1140: pointer being freed was not allocated
root.exe(4111,0x10c9d15c0) malloc: *** set a breakpoint in malloc_error_break to debug

To reprooduce in FairRoot:
1. go to examples/advanced/propagator/macros
2. execute root -l -q ‘runMC.C(1000)’ // may add more events to see the segmentation violation in step 3.
3. execute root -l -q 'runProp.C("geane")'

**Comment by karabowi** [comment]
The fix to this problem is: 

`diff --git a/erdecks/ertrak.F b/erdecks/ertrak.F
index 3fb0813..fa95cb1 100644
--- a/erdecks/ertrak.F
+++ b/erdecks/ertrak.F
@@ -78,8 +78,8 @@
 *     
 * *** Decode character option
 *
-      CHOPTI = CHOPT
-      CALL UOPTC (CHOPT, 'BELMOPVX', IOPT)
+      CHOPTI = CHOPT(1:len(CHOPT))
+      CALL UOPTC (CHOPTI, 'BELMOPVX', IOPT)
 *
       IF (IOPTB.EQ.0) THEN
          BACKTR = 1.
`

**Comment by dennisklein** [comment]
Could you please open a PR to FairRootGroup/geant3 against the master branch? Probably makes more sense if you are the author in the git history, in case there are future references to it. Because I have very little knowledge of Fortran and would be a rather useless contact^^

**Comment by karabowi** [comment]
Would it be better to do a patch in FairSoft nov20 release, or do a PR to our fork of geant3?

**Comment by dennisklein** [comment]
I will make a patch for the `nov20p1`, but in the `feb20` release I would like to bump the version in our fork of geant3. But even for the patch in `nov20p1` I prefer to take the patch file from the git repo already with proper metadata.

**Comment by karabowi** [comment]
I've made a PR to the geant3/master, on
https://github.com/FairRootGroup/geant3/pull/1

**Comment by dennisklein** [comment]
The fix is integrated in the `nov20_patches` branch (8c472d4e98ee4842f05545e76ee83830fad9b5b6) and will be included in the next patch release.
