### ISSUE TITLE
[spack][nov20] c++11 not recognised on Debian 8.11 (jessie)?

### ISSUE THREAD

**Issue by RalfKliemt** [FairRootGroup/FairSoft#373]
Hi,

I am trying to install the new release on a Debian 8 test machine at GSI (gcc 4.9.2).
I get the following type of errors:
`In file included from /usr/include/c++/4.9/atomic:38:0,
                 from /tmp/kliemt/spack-stage/spack-stage-ftgl-2.4.0-qla6wfxrftjtbngapib62bologa7x7ln/spack-src/src/FTGL/FTLibrary.h:36,
                 from /tmp/kliemt/spack-stage/spack-stage-ftgl-2.4.0-qla6wfxrftjtbngapib62bologa7x7ln/spack-src/src/FTGL/ftgl.h:137,
                 from /tmp/kliemt/spack-stage/spack-stage-ftgl-2.4.0-qla6wfxrftjtbngapib62bologa7x7ln/spack-src/src/FTFace.h:33,
                 from /tmp/kliemt/spack-stage/spack-stage-ftgl-2.4.0-qla6wfxrftjtbngapib62bologa7x7ln/spack-src/src/FTCharmap.cpp:29:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
`
Cheers!
  Ralf

**Comment by dennisklein** [comment]
While this particular error might be solvable, you will encounter other problems on later packages with the system compiler on Debian 8. It is too old.

We support the FairSoft installation with a newer GCC from cvmfs on GSI Debian 8, see the following files on how to setup your system and spack:

https://github.com/FairRootGroup/FairSoft/blob/master/test/container/gsi-debian.8.def
https://github.com/FairRootGroup/FairSoft/blob/master/test/container/gsi-debian-8-gcc.yaml
