### ISSUE TITLE
Xercesc location moved

### ISSUE THREAD

**Issue by olantwin** [FairRootGroup/FairSoft#38]
Hi,

Xercesc has seen a new release (3.1.3), which results in the version 3.1.2 archives not being available at the location the install script expects (as defined by the `package_versions.sh`).

The version expected is available in the Apache archives at: <https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.1.2.tar.gz>

As a workaround until this is fixed, downloading the package manually and placing it in `FairSoft/basics` satisfied the install script.

Cheers

**Comment by fuhlig1** [comment]
Thanks for the information about the problem and how to fix it.

The new location is now used for the dev, master, jul15_patches and mar15_patches branches as well as for the releases mar15p4, jul15p4 and nov15p3.
