### ISSUE TITLE
[dev and nov20_patches][legacy] patch for pythia6 not working

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#387]
Installation on OSX Catalina fails for an unknown patch option `--merge`.
```
CMake Error at /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/Stamp/pythia6/pythia6-patch-RelWithDebInfo.cmake:37 (message):
  Command failed: 2

   '/usr/bin/patch' '--merge' '-p1' '-i' '/Users/tstockmanns/PandaSoftware/FairSoft/dev/source/legacy/pythia6/add_missing_extern_keyword.patch'

  See also

    /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/Log/pythia6-patch.log


-- Log output is:
/usr/bin/patch: unrecognized option `--merge'
/usr/bin/patch: Try `/usr/bin/patch --help' for more information.

CMake Error at /Users/tstockmanns/PandaSoftware/FairSoft/dev/build/Stamp/pythia6/pythia6-patch-RelWithDebInfo.cmake:47 (message):
  Stopping after outputting logs.
```

**Comment by fuhlig1** [comment]
Hi Tobias,

you have to install the gpatch package from brew which provides the needed features.

**Comment by TobiasStockmanns** [comment]
With gpatch it is working.

**Comment by TobiasStockmanns** [comment]
It would be good to have this written in the installation instructions somewhere.

**Comment by dennisklein** [comment]
> It would be good to have this written in the installation instructions somewhere.

https://github.com/FairRootGroup/FairSoft/blob/nov20_patches/legacy/README.md#1-install-system-dependencies

---

Also note that I am not sure any FairSoft is currently working on macOS. `dev` might be the closest to "working" but there are unsolved issues still.

**Comment by TobiasStockmanns** [comment]
@dennisklein thank you for pointing this out. Usually I have the dependencies installed but it might be that they are still from an older version or that the system somehow had a wrong PATH set pointing to the original `patch` program from OSX.

**Comment by ChristianTackeGSI** [comment]
> Also note that I am not sure any FairSoft is currently working on macOS. `dev` might be the closest to "working" but there are unsolved issues still.

FairSoft spack edition is working mostly on macos at the moment.
Major issue remaining: https://github.com/FairRootGroup/FairMQ/issues/339 (not an issue in FairMQ, but a support request there).
