### ISSUE TITLE
Compilation problem on Mac OS 11.2.3

### ISSUE THREAD

**Issue by aliyilmaz1** [FairRootGroup/FairSoft#392]
I followed the procedure in the given below;
```
**NEW::::fairSoft + FairRoot + PandaRoot:::::**
##################################################################
A.  Installing macports
################################
Install Xcode and the Xcode Command Line Tools (from AppStore)
>> sudo xcode-select --install

**installing brew;** 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update
 and install its dependencies as given in "dependencies_macos.md"
```
I tried to install FairSoft (jun19p2/ jun19_patches) but it gives an error 
```
**"[100%] Linking CXX shared library libgeant321.dylib
ld: library not found for -lfreetype
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgeant321.dylib] Error 1"**
```

then:  tried to test the latest releases of FairSoft (nov20) , FairRoot (v18.6.0) and PandaRoot (dev).

I successfully installed  FairSoft (nov20) , FairRoot (v18.6.0) but PandaRoot (dev) fails at compilation stage with the error—>>  `**ld: library not found for -lfreetype**`

in terminal:
```
mkdir programFiles
cd programFiles
mkdir PandaSoftwares
cd $HOME/programFiles/PandaSoftwares
mkdir FairSoft 
```
::::::::::::::::::::FairSoft:::::::::::::::::::
```
cd FairSoft; git clone -b nov20 https://github.com/FairRootGroup/FairSoft nov20  ;
cd nov20 ; git checkout -b nov20 ; mkdir build install;    
./legacy/setup-macos.sh
cmake -S. -Bbuild  -DCMAKE_INSTALL_PREFIX=./install;
cmake --build ./build -j 16 ;
export SIMPATH=$HOME/programFiles/PandaSoftwares/FairSoft/install; echo $SIMPATH
```

:::::::::::::::FairRoot:::::::::::::::::::
```	
cd FairSoft; git clone -b v18.6.0 https://github.com/FairRootGroup/FairSoft v18.6.0  ;
cd v18.6.0 ; git checkout -b v18.6.0 ; mkdir build install;  
cmake -S. -Bbuild  -DCMAKE_INSTALL_PREFIX=./install;
cmake --build ./build -j 16 ;

export FAIRROOTPATH=/$HOME/programFiles/PandaSoftwares/FairRoot/v18.6.0/install

echo $SIMPATH; echo $FAIRROOTPATH 
```
::::::::::::::::PandaRoot::::::::::::::::::::::
```
mkdir PandaRoot; cd PandaRoot ; git clone -b dev https://git.panda.gsi.de/PandaRootGroup/PandaRoot.git
cd dev
git checkout -b dev
mkdir build
cd build
cmake ../
 
**"[100%] Linking CXX shared library libgeant321.dylib
ld: library not found for -lfreetype
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgeant321.dylib] Error 1"**
```

After communicating with  @TobiasStockmanns, I follow his suggestions but no success at the ends so he suggested to open an issue at here.
1. ============
When I changed to nov20_patches branch and installed the dependency of this, then  I got the glew error at the compilation stage of the ROOT.
```
**"[ 93%] Linking CXX shared library ../../lib/libRGL.so
Undefined symbols for architecture x86_64:
  "___GLEW_EXT_framebuffer_multisample", referenced from:
      TGLFBO::Init(int, int, int) in TGLFBO.cxx.o"**
```
If I add the lines in  legacy.cmake of nov20_patches with dev versions 
```
…..
 if(APPLE AND CMAKE_VERSION VERSION_GREATER 3.15)
    set(root_builtin_glew "-Dbuiltin_glew=ON")
  endif()
  if(APPLE)
    set(root_cocoa "-Dcocoa=ON")
    set(root_x11 OFF)
  else()
    unset(root_cocoa)
    set(root_x11 ON)
  endif()
…...
```
Which leads to same results (glew error ???).

2. ====================================
2.1.	I installed (/compile) fairSoft/dev (mar21) version successfully.
2.2. tried to compile FairRoot v18.6.0 / v18.6.1 / dev versions
but all leads to error
```
**error: implicit instantiation of undefined template 'std::__1::hash<fair::mq::Transport>'
    : public integral_constant<bool, __is_empty(_Tp)> {};**
```

thank you
Ali

**Comment by dennisklein** [comment]
Thanks for your report. Most of those problems (except the freetype one) are already known and there are no solutions known/implemented at this point in time. Unfortunately, FairSoft currently does not work on macOS 10.15 and 11 with Xcode 12. And even if you get everything compiled, there are still problems with the root interpreter. We hope we can provide patch releases for `nov20` and for the upcoming release (mar21 or apr21) in the future which eventually fix those issues.

**Comment by dennisklein** [comment]
related FairRootGroup/FairMQ#339

**Comment by dennisklein** [comment]
Please try the latest `apr21` release on macOS 11:

1. Install the latest CommandLineTools for Xcode (`12.4`) (from https://developer.apple.com/downloads, requires Apple account)
2. Install [Homebrew](https://brew.sh/), then run:
```
brew update
brew upgrade
brew doctor   # address any issue until it prints "Your system is ready to brew."
```

3. Install (pre-compiled) FairSoft via Homebrew:

```
brew tap fairrootgroup/fairsoft
brew install fairsoft@21.4
export SIMPATH=$(brew --prefix fairsoft@21.4)
```
4. Install FairRoot
```
git clone -b master https://github.com/FairRootGroup/FairRoot FairRoot_source
cmake -S FairRoot_source -B FairRoot_build -DCMAKE_INSTALL_PREFIX=./FairRoot_install
cmake --build FairRoot_build --target install -j <ncpus>
export FAIRROOTPATH="$(pwd)/FairRoot_install"
```
5. Continue with PandaRoot

---

Alternative to step 3 above, you may install FairSoft from source, e.g.:

Follow 1. and 2. exactly from above, then instead of step 3 do the following:
a. Clone FairSoft repo and install system dependencies
```
git clone -b apr21_patches https://github.com/FairRootGroup/FairSoft FairSoft_source
FairSoft_source/legacy/setup-macos.sh
```
b. Modify `FairSoft_source/FairSoftConfig.cmake` to your needs, see the comments inside this file.
c. Configure and compile:
```
cmake -S FairSoft_source -B FairSoft_build -C FairSoft_source/FairSoftConfig.cmake
cmake --build FairSoft_build -j <ncpus>
```
d. `export SIMPATH=<install-dir>` - Replace `<install-dir>` with the value you chose in `FairSoft_source/FairSoftConfig.cmake`

Continue with steps 4. and 5. from above.

---

See also the [full manual](https://github.com/FairRootGroup/FairSoft#readme). `nov20` is still broken on macOS, I will take a look at it in the next weeks whether it is feasible to repair.

**Comment by dennisklein** [comment]
Closing, because abandoned. Re-open, if you still have questions or something does not work.
