### ISSUE TITLE
[legacy][nov20] Install without sudo 

### ISSUE THREAD

**Issue by MadNazgul** [FairRootGroup/FairSoft#396]
Good day,

I have no sudo access to system, all dependencies install to my home directory and define environment variables to this folders. In process of installation with CMake get errors with undefined xerces package. I resolved this with define `XercesC_LIBRARY` and `XercesC_INCLUDE_DIR` in `*-configure-Release.cmake` files before execution `make` command.

Perhaps there is another way to set the required variables without changing the cmake-files?

Thank you!

**Comment by dennisklein** [comment]
> install to my home directory and define environment variables to this folders

Can you please provide more details which Xerces version you installed and which environment variables you defined? Thank you!

**Comment by MadNazgul** [comment]
Xerces version is 3.2.3. Variables are `XERCESROOT`, `PATH`, `C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH`, `LIBRARY_PATH`, `LD_LIBRARY_PATH`. And one of iteration try to define `XercesC_LIBRARY` and `XercesC_INCLUDE_DIR`, but it didn't work for me.

**Comment by dennisklein** [comment]
> Variables are XERCESROOT, PATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, LIBRARY_PATH, LD_LIBRARY_PATH.

Setting (if it is set, prepending to) [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) pointing to the Xerces install prefix should be enough.

**Comment by MadNazgul** [comment]
I am setting ``CMAKE_PREFIX_PATH``, but it always gets passed to ``CMAKE_PREFIX_PATH: UNINITIALIZED`` variable.
In all the generated cmake-files, ``CMAKE_PREFIX_PATH`` remains like ``CMAKE_INSTALL_PREFIX``.
How do I change it? I can not find a solution in Google :(

**Comment by dennisklein** [comment]
> I am setting `CMAKE_PREFIX_PATH`, but it always gets passed to `CMAKE_PREFIX_PATH: UNINITIALIZED` variable.
> In all the generated cmake-files, `CMAKE_PREFIX_PATH` remains like `CMAKE_INSTALL_PREFIX`.
> How do I change it? I can not find a solution in Google :(

You are right, it is not forwarded properly, try the following patch:

```diff
diff --git a/cmake/legacy.cmake b/cmake/legacy.cmake
index bd8a5a9b59..24e82cf486 100644
--- a/cmake/legacy.cmake
+++ b/cmake/legacy.cmake
@@ -33,7 +33,7 @@ include(ExternalProject)
 set_property(DIRECTORY PROPERTY EP_BASE ${CMAKE_BINARY_DIR})
 set(CMAKE_DEFAULT_ARGS CMAKE_CACHE_DEFAULT_ARGS
   "-DBUILD_SHARED:BOOL=ON"
-  "-DCMAKE_PREFIX_PATH:STRING=${CMAKE_INSTALL_PREFIX}"
+  "-DCMAKE_PREFIX_PATH:STRING=${CMAKE_INSTALL_PREFIX}:${CMAKE_PREFIX_PATH}"
   "-DCMAKE_INSTALL_PREFIX:STRING=${CMAKE_INSTALL_PREFIX}"
   "-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON"
   "-DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON"
```

If this does not work, try a `;` instead of `:` as separator. Let me know if and which patch works for you, then I can add it, that your use case is supported from now on.

**Comment by dennisklein** [comment]
If you set it as environment variable, it needs to be

```diff
diff --git a/cmake/legacy.cmake b/cmake/legacy.cmake
index bd8a5a9b59..24e82cf486 100644
--- a/cmake/legacy.cmake
+++ b/cmake/legacy.cmake
@@ -33,7 +33,7 @@ include(ExternalProject)
 set_property(DIRECTORY PROPERTY EP_BASE ${CMAKE_BINARY_DIR})
 set(CMAKE_DEFAULT_ARGS CMAKE_CACHE_DEFAULT_ARGS
   "-DBUILD_SHARED:BOOL=ON"
-  "-DCMAKE_PREFIX_PATH:STRING=${CMAKE_INSTALL_PREFIX}"
+  "-DCMAKE_PREFIX_PATH:STRING=${CMAKE_INSTALL_PREFIX}:$ENV{CMAKE_PREFIX_PATH}"
   "-DCMAKE_INSTALL_PREFIX:STRING=${CMAKE_INSTALL_PREFIX}"
   "-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON"
   "-DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON"
```

**Comment by MadNazgul** [comment]
Sorry for late answer, vacations.

I tried all the options you suggested: with and without `$ENV{}` in `legacy.cmake`, with `:` and `;`.

The last configuration attempt was like this (I define `CMAKE_PREFIX_PATH` to all variables of xerces directory like environment variable and add its to `cmake`)
```
$ export CMAKE_PREFIX_PATH="/path/to/xerces:/path/to/xerces/lib64:/path/to/xerces/lib64/pkgconfig:/path/to/xerces/lib64/cmake:/path/to/xerces/lib64/cmake/XercesC"
$ CMAKE_PREFIX_PATH="/path/to/xerces/lib64:/path/to/xerces/lib64:/path/to/xerces/lib64/pkgconfig:/path/to/xerces/lib64/cmake:/path/to/xerces/lib64/cmake/XercesC" cmake -DCMAKE_PREFIX_PATH="/path/to/xerces:/path/to/xerces/lib64:/path/to/xerces/lib64/pkgconfig:/path/to/xerces/lib64/cmake:/path/to/xerces/lib64/cmake/XercesC" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/BUILD/fairsoft_nov20/fairsoft_build ..
```

The option to install the Xerces library via `yum install` command worked.

**Comment by dennisklein** [comment]
> 
> The option to install the Xerces library via `yum install` command worked.

1. Do you have `sudo` access now?
2. Do you need further assistance with the case when not having `sudo` access?

**Comment by MadNazgul** [comment]
I have `sudo` access only on some test servers of the cluster, but not main part of cluster. I would be very grateful for the assistance with this case.

**Comment by MadNazgul** [comment]
For this moment I was able to build FairSoft by adding `XERCESC_ROOT_DIR` variable to `legacy.cmake` in part of build Geant4. But it's workaround.

**Comment by dennisklein** [comment]
The following works:

```
$ git clone -b dev https://github.com/FairRootGroup/FairSoft
$ cd FairSoft
$ podman run -it --name fairsoft_xerces_test -v.:/root --privileged docker://fedora:34 bash -l
[root@aad29ee0697b /] # cd /root
[root@aad29ee0697b ~] # legacy/setup-fedora.sh
[root@aad29ee0697b ~] # dnf -y remove xerces-c
[root@aad29ee0697b ~] # git clone -b v3.2.3 https://github.com/apache/xerces-c
[root@aad29ee0697b ~] # cmake -S xerces-c -B xerces-c-build -DCMAKE_INSTALL_PREFIX=xerces-c-install
[root@aad29ee0697b ~] # cmake --build xerces-c-build --target install -j8
[root@aad29ee0697b ~] # export CMAKE_PREFIX_PATH=/root/xerces-c-install
[root@aad29ee0697b ~] # cmake -S. -Bbuild -CFairSoftConfig.cmake
[root@aad29ee0697b ~] # cmake --build build --target geant4-configure -j8
(...)
[100%] Performing configure step for 'geant4'
-- geant4 configure command succeeded.  See also /root/build/Log/geant4-configure-*.log
[root@aad29ee0697b ~] # grep XercesC build/Log/geant4-configure.log
-- Found XercesC: /root/xerces-c-install/lib64/libxerces-c.so (found version "3.2.3")
```

Re-open, if you have still questions.
