### ISSUE TITLE
Missing library libG4clhep.so

### ISSUE THREAD

**Issue by MadNazgul** [FairRootGroup/FairSoft#413]
Good day,

in previous versions there was a library `libG4clhep.so`. I did not find it in the new version. Tell me, please, what was it replaced with?

Thank you!

**Comment by fuhlig1** [comment]
Hi,

Geant4 can either use an external installation of CLHEP or compile it one version. In the second case of the internal CLHEP library the resulting library is called libG4clhep.so. In newer versions we compile and install the library from the CLHEP project which is called libCLHEP.so. You find the library in the lib directory of your FairSoft installation.

**Comment by MadNazgul** [comment]
Thank you!
