### ISSUE TITLE
TEve window on El Capitan

### ISSUE THREAD

**Issue by geniejhang** [FairRootGroup/FairSoft#42]
As you might already know, when you move your cursor crossing the TEve window border, ROOT crashes.

This was fixed on ROOT 6.06.
https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=20649&p=89210#p89210

Is there any plan to update the ROOT version in FairSoft to the version?

**Comment by MohammadAlTurany** [comment]
Hallo Genie,
If you switch to the dev branch it is already there!
best,
Mohammad

**Comment by geniejhang** [comment]
Thank you, Mohammad.

Then, what I have to do is just wait until release :)

**Comment by MohammadAlTurany** [comment]
Hallo Genie,
If you do not went to use the dev branch, then yes.
Best,
Mohammad
