### ISSUE TITLE
[legacy][apr21_patches] error with Geant3

### ISSUE THREAD

**Issue by MadNazgul** [FairRootGroup/FairSoft#427]
In our application, which uses Geant3 with this versions of FairSoft/FairRoot, we always got error about ZEBRA
```
Error in <TGeant3TGeo::SetParticle>: Particle already exists.

 !!!!! ZFATAL called from MZTABC
              called from MZTABR
              called from MZGAR1
              called from MZLIFT
              called from MZBOOK

 !!!!! ZFATAL reached from MZTABC    for Case=  1

          IQUEST(11) =   4997234           4C4072
          IQUEST(12) =   4997101           4C3FED
          IQUEST(13) =   4999968           4C4B20

          Current Store number =  0  (JQDIVI=20)
1ZEBRA SYSTEM Post-Mortem from ZPOSTM.
```

On version june19p1 we had the similar problem with compilers 7.3.0 and newer. After we switchig the compiler to 4.8.5 the problem dissapeared. But on current version of FairSoft using 4.8.5 is impossible due to requirements to gcc c++17.

```
uname -srm
Linux 3.10.0-1160.15.2.el7.x86_64 x86_64
```

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=~/BUILD/fair-apr21_patches-gcc112/gcc-11.2.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc_src/configure --enable-languages=c,c++,fortran --disable-multilib --enable-bootstrap --enable-stage1-languages=all --enable-shared --enable-libquadmath --enable-libquadmath-support --enable-threads --enable-tls --enable-nls --enable-lto CFLAGS=-m64 CXXFLAGS=-m64 --prefix=~/BUILD/fair-apr21_patches-gcc112/gcc-11.2.0
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC)
```

Packages
CMake 3.21.1
Git 2.26.2
Python 3.8.2
Readline 8.1
SQlite 3.34.1
FFTW 3.3.9
GSL 2.7
libICE 1.0.10
libSM 1.2.3
libXpm 3.5.13
PostgreSQL 13.2
Xerces 3.2.3
zlib 1.2.11

FairSoft version apr21_patches
Builded with option `-DGEANT4MT=OFF`

FairRoot version 18.4.2
Builded with options `-DGSL_CONFIG_EXECUTABLE=path/to/gsl-2.7/gsl-config` and `-DBUILD_EXAMPLES=OFF`

Initialized all sprcific variables (SIMPATH, FAIRROOTPATH).

**Comment by dennisklein** [comment]
A `!!!!! ZFATAL called from MZTABC` error was also discussed in https://github.com/FairRootGroup/FairRoot/issues/686#issuecomment-347858103, if I understand it correctly, building Geant3 without optimizations on newer compilers might help.

E.g. apply the following:
```diff
diff --git a/cmake/legacy.cmake b/cmake/legacy.cmake
index 8ebf02ea06..75f8bff212 100644
--- a/cmake/legacy.cmake
+++ b/cmake/legacy.cmake
@@ -370,6 +370,7 @@ if(PACKAGE_SET STREQUAL full)
     GIT_REPOSITORY https://github.com/FairRootGroup/geant3 GIT_TAG v${geant3_version}
     ${CMAKE_DEFAULT_ARGS} CMAKE_ARGS
       "-DBUILD_GCALOR=ON"
+      "-DCMAKE_BUILD_TYPE=Debug"
     DEPENDS root vmc ${extract_source_cache_target}
     ${LOG_TO_FILE}
   )
```

Let us know if this helps.

**Comment by dennisklein** [comment]
If you could provide a small reproducer, we can also try to find which gcc optimization is causing this issue and only disable this one instead of disabling all optimizations.

**Comment by MadNazgul** [comment]
It is not so easy to work with it. We use it inside software package of our experiment. This package is too large

**Comment by MadNazgul** [comment]
Thanks a lot. It works correct with `-DCMAKE_BUILD_TYPE=Debug`.
