### ISSUE TITLE
DDS installation and PIE object issue

### ISSUE THREAD

**Issue by bzhantoine** [FairRootGroup/FairSoft#436]
Hello everybody,

I try to install FairSoft (jun19p2.tar.gz), I use Linux: Ubuntu 20.04.3 LTS.
The following error appears, I have searched in open and closed issues and nothing has helped me so far:

```
[ 89%] Built target dds-commander
[ 90%] Built target dds-submit-localhost
[ 91%] Built target dds-submit-slurm
[ 93%] Built target dds-submit-ssh
[ 94%] Built target dds-submit-pbs
[ 96%] Built target dds-submit-lsf
/usr/bin/ld: CMakeFiles/dds-scheduler-tests.dir/TestScheduler.cpp.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: CMakeFiles/dds-scheduler-tests.dir/__/src/AgentChannel.cpp.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: CMakeFiles/dds-scheduler-tests.dir/__/src/ChannelId.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN5boost5uuids13entropy_errorE' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: CMakeFiles/dds-scheduler-tests.dir/__/src/SSHScheduler.cpp.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make[2]: *** [dds-commander/tests/CMakeFiles/dds-scheduler-tests.dir/build.make:159: dds-commander/tests/dds-scheduler-tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:1186: dds-commander/tests/CMakeFiles/dds-scheduler-tests.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
*** ERROR: DDS could not be created.
*** End installation of external packages with Errors***
```

Thank you in advance for your help.

**Comment by dennisklein** [comment]
Can you please attach the file `basics/DDS/build/CMakeCache.txt` for further debugging. Thx!

**Comment by bzhantoine** [comment]
[CMakeCache.txt](https://github.com/FairRootGroup/FairSoft/files/7466810/CMakeCache.txt)

**Comment by dennisklein** [comment]
What is the output of `/usr/bin/g++ --version`?

**Comment by dennisklein** [comment]
I suspect a problem with your compiler installation, CMake detects executables from a gcc version 5 installation in your system. When I compare your `CMakeCache.txt` against mine, I see:

```diff
184c184
< CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-9
---
> CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-5
188c188
< CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-9
---
> CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-5
210c210
< CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-9
---
> CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-5
214c214
< CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-9
---
> CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-5
```

**Comment by bzhantoine** [comment]
I changed several times the version of gcc and g++ during the installation to solve some problems, a tip from a colleague who succeeded in this installation. This error remains regardless of the version used... even if I change the corresponding lines (the ones you indicated me).

**Comment by dennisklein** [comment]
So far I could not reproduce the problem. I tried the installation on a fresh ubuntu 20.04.3 installation on x86_64 and it worked fine.

One scenario I could imagine is, if your ubuntu is an upgraded version from an older version, maybe there is an old config still left over in the system somewhere which somehow interferes with the PIE flag. IIRC gcc switched it on by default since version 5. Have you checked if there is any suspicious environment variable set?

**Comment by bzhantoine** [comment]
I'm using a laptop provided for my PhD, so I don't have all the information about its older versions of ubuntu. 
I haven't checked the environment variables set yet, but if I start this installation again keeping in mind the versions of gcc and g++ (choosing the last one available on my laptop: 9), it could be OK according to you?

**Comment by dennisklein** [comment]
> ... if I start this installation again keeping in mind the versions of gcc and g++ (choosing the last one available on my laptop: 9), it could be OK according to you?

Yes, it works for me. Make sure you have installed all the packages listed in `dependencies.md`, too. Also do a `git clean -ffdx` to start from scratch after changing the compiler.

**Comment by bzhantoine** [comment]
Thanks for your advice, one last question: did you install the third patch from FairSoft released in June 19?
Do you advise me to choose the last one (Nov21)?

**Comment by dennisklein** [comment]
> Thanks for your advice, one last question: did you install the third patch from FairSoft released in June 19?

I used the [`jun19p2` tag](https://github.com/FairRootGroup/FairSoft/tree/jun19p2), but commented out almost all packages except CMake, Boost, and DDS in [`configure.sh` line 205 ff.](https://github.com/FairRootGroup/FairSoft/blob/jun19p2/configure.sh#L205).

> Do you advise me to choose the last one (Nov21)?

Not sure what you mean. In general, I advise to use the latest patch release from any chosen major release.
