### ISSUE TITLE
Error in installing fairmq (apr21p1)

### ISSUE THREAD

**Issue by vfriese** [FairRootGroup/FairSoft#438]
I am trying to install fairsoft apr21p1 on MacOS 10.14.6., following the recipes in /legacy. The installation terminates at fairmq:
```

[ 85%] Performing update step for 'fairmq'
-- fairmq update command succeeded.  See also /Users/vfriese/temp/fairsoft/build/Log/fairmq-update-*.log
[ 85%] No patch step for 'fairmq'
[ 85%] Performing configure step for 'fairmq'
CMake Error at /Users/vfriese/temp/fairsoft/build/Stamp/fairmq/fairmq-configure-RelWithDebInfo.cmake:37 (message):
  Command failed: 1

   '/Applications/CMake.app/Contents/bin/cmake' '-DBUILD_DDS_PLUGIN=ON' '-DBUILD_SDK_COMMANDS=ON' '-DBUILD_SDK=ON' '-GUnix Makefiles' '-C/Users/vfriese/temp/fairsoft/build/tmp/fairmq/fairmq-cache-RelWithDebInfo.cmake' '/Users/vfriese/temp/fairsoft/build/Source/fairmq'

  See also

    /Users/vfriese/temp/fairsoft/build/Log/fairmq-configure.log

-- Log output is:
loading initial cache file /Users/vfriese/temp/fairsoft/build/tmp/fairmq/fairmq-cache-RelWithDebInfo.cmake
-- Found Git: /usr/bin/git (found version "2.21.1 (Apple Git-122.3)") 
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- FairMQ 1.4.33 from Tue Mar 23 13:00:35 2021 +0100
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Building bundled asio
CMake Error at cmake/FairMQLib.cmake:470 (message):
  128

  See also
  "/Users/vfriese/temp/fairsoft/build/Build/fairmq/extern/asio/build.log" 
Call Stack (most recent call first):
  cmake/FairMQLib.cmake:484 (exec_source)
  CMakeLists.txt:138 (build_bundled)

-- Configuring incomplete, errors occurred!
See also "/Users/vfriese/temp/fairsoft/build/Build/fairmq/CMakeFiles/CMakeOutput.log".

CMake Error at /Users/vfriese/temp/fairsoft/build/Stamp/fairmq/fairmq-configure-RelWithDebInfo.cmake:47 (message):
  Stopping after outputting logs.

make[2]: *** [Stamp/fairmq/fairmq-configure] Error 1
make[1]: *** [CMakeFiles/fairmq.dir/all] Error 2
make: *** [all] Error 2
```

The content of the file /Users/vfriese/temp/fairsoft/build/Build/fairmq/extern/asio/build.log is:
```

>>> /usr/bin/git submodule update --init -- /Users/vfriese/temp/fairsoft/build/Source/fairmq/extern/asio
fatal: /Users/vfriese/temp/fairsoft/build/Source/fairmq/extern/asio: '/Users/vfriese/temp/fairsoft/build/Source/fairmq/extern/asio' is outside repository
```

Any idea or suggestion?

**Comment by dennisklein** [comment]
Which git version are you using?

**Comment by vfriese** [comment]
git version 2.21.1 (Apple Git-122.3)

**Comment by dennisklein** [comment]
Two guesses:
1. git is confused by capitalization or encoding of your directory names
   * What does `git config -l` print?
   * Are you using case-sensitive or case-in-sensitive file system?
2. Something went wrong with the cloning of the FairMQ repo
   * To exclude this, run `rm -rf /Users/vfriese/temp/fairsoft/build/{Source,Build,Stamp}/fairmq` and then run the FairSoft build step again

**Comment by vfriese** [comment]
1. case-insensitive (APFS standard)
vfriese [Volkers-MacBook-Pro:~/temp/fairsoft/build] git config -l

credential.helper=osxkeychain
user.name=Volker Friese
user.email=v.friese@gsi.de
branch.autosetuprebase=always
core.ignorecase=false

2. I did; same result

**Comment by dennisklein** [comment]
According to https://github.com/microsoft/vscode/issues/88890 the `core.ignorecase=false` may be the cause.

**Comment by vfriese** [comment]
How can I reset this option? 

I use git since years on my Mac, never came across this issue.

**Comment by dennisklein** [comment]
`git config --global core.ignorecase true` or similar

> I use git since years on my Mac, never came across this issue.

Seems to be related to git submodules

**Comment by vfriese** [comment]
I have edited ~vfriese/.gitconfig, and now git config -l gives

```
credential.helper=osxkeychain
user.name=Volker Friese
user.email=v.friese@gsi.de
branch.autosetuprebase=always
core.ignorecase=true
```

Still, same result (after removing build/{Source, Build, Stamp}/fairmq

**Comment by vfriese** [comment]
I'll try from scratch (configuring) with this setting. Will take a while.

**Comment by dennisklein** [comment]
no need to try from scratch really

**Comment by vfriese** [comment]
Maybe, but at least I am now beyond configuring fairmq:

```
[ 66%] Creating directories for 'fairmq'
[ 71%] Performing download step (git clone) for 'fairmq'
-- fairmq download command succeeded.  See also /Users/vfriese/Temp/fairsoft/build/Log/fairmq-download-*.log
[ 71%] Performing update step for 'fairmq'
-- fairmq update command succeeded.  See also /Users/vfriese/Temp/fairsoft/build/Log/fairmq-update-*.log
[ 71%] No patch step for 'fairmq'
[ 71%] Performing configure step for 'fairmq'
-- fairmq configure command succeeded.  See also /Users/vfriese/Temp/fairsoft/build/Log/fairmq-configure-*.log
[ 71%] Performing build step for 'fairmq'
```

Ten meters to ground, still looking good...

Assuming it runs through now, I conclude:

The issue was indeed the git config core.ignorecase, which has to be set true in my case of a case-insensitive file system. The change takes effect only when re-running the cmake configure step, not only the build step.

**Comment by dennisklein** [comment]
> The change takes effect only when re-running the cmake configure step, not only the build step.

yes, makes sense, if the configure step is re-cloning the fairmq repo, which certainly happened when you started from scratch.

**Comment by vfriese** [comment]
OK, build of fairmq is completed. Many thanks for your quick help, also in such odd hours.
