### ISSUE TITLE
ARM64 compilation of GEANT3

### ISSUE THREAD

**Issue by fegray** [FairRootGroup/FairSoft#442]
To compile on ARM64 linux (a Linux VM on a MacBook with the Apple M1 processor), I had to change the first line of FairSoft-build/Source/geant3/added/dummies.c slightly:

#if (defined(__linux) && !defined(__ia64) && !defined(__aarch64__))

**Comment by dennisklein** [comment]
Thank you! However, I suggest to report this directly with our upstream geant3 project: https://github.com/vmc-project/geant3. This is generic and will benefit a lot more users in the community this way.
