### ISSUE TITLE
Failed to download boost and pythia8 packages by CMake scripts

### ISSUE THREAD

**Issue by huagenxu** [FairRootGroup/FairSoft#444]
It happened that the boost and pythia8 packages can't be downloaded properly by CMake properly. 
It failed to download the package of boost_1_68_0 or boost_1_75_0. 
Similar case happened to pythia8, e.g., pythia8240 and pythia8303. 

For boost, the given url: https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 did not work anymore. 
For pythia8, the given url: http://home.thep.lu.se/~torbjorn/pythia8/pythia8303.tgz is not valid anymore.
Both url should be updated

**Comment by dennisklein** [comment]
Which git branch of FairSoft are you using?

**Comment by huagenxu** [comment]
The git branch is master and the FairSoft versions are FairSoft_jun19p2 and FairSoft_apr21, respectively.

**Comment by fuhlig1** [comment]
Why don't you use the latest jun19 patch release which exactly fixes the two download locations, or the latest apr21 patch where the locations are also fixed?

**Comment by huagenxu** [comment]
Indeed I have solved the problem by downloading the files separately. The idea to report the problem is update the download link in the relevant files. So if this was already updated there is no problem any more.

**Comment by fuhlig1** [comment]
It is solved in the latest patch versions. You should always use the latest patch versions since normally issues are already fixed.

I close the issue.
