### ISSUE TITLE
ROOT with FFTW required for PandaROOT

### ISSUE THREAD

**Issue by BSali** [FairRootGroup/FairSoft#445]
PandaROOT will require ROOT with FFTW enabled in the near future.

As it turns out from a brief discussion on the mattermost channel, it seems that only macOS includes FFTW as dependency (legacy/setup-macos.sh) atm. It would be helpful if FFTW is included for all OS.

**Comment by dennisklein** [comment]
ToDo in FairSoft:
* [ ] Add appropriate fftw packages to all `legacy/setup-*.sh` scripts
* [ ] Check, if we need to enable this in the Root configure step explicitely or if it is reliable enough, if we let Root auto-enable it.

@BSali @RalfKliemt I think it would also be useful to express this required dependency in the PandaRoot CMake. It is possible to specify this in the `find_package` call, e.g. `find_package(ROOT COMPONENTS fftw3)` - however, there is also a component `builtin_fftw3` exposed in the `ROOTConfig.cmake`. Hopefully, requiring `fftw3` component is enough and matches ROOT installations with either external or builtin fftw3 libs.
* [ ] We need to clarify the exact behaviour.

**Comment by ChristianTackeGSI** [comment]
Okay, I am just looking into adding fftw support to ROOT in our spack setup.

fftw in spack has mpi support (and it's enabled by default), which pulls in a lot of dependencies. So the question is: Do you need fftw with MPI support? Or does ROOT support that at all?

**Comment by BSali** [comment]
Sorry for the late reply: 
 We do not need fftw with MPI support.
