### ISSUE TITLE
Event display for simulations fails

### ISSUE THREAD

**Issue by jose-luis-rs** [FairRootGroup/FairSoft#446]
Hello

I have installed new versions of FairSoft and FairRoot in my computer:
FairSoft: apr21p2
FairRoot: v18.6.6
and the event display for simulations, for example:
FairRoot/examples/simulation/rutherford/macros/eventDisplay.C
does not work. When I execute it the terminal shows these errors:
root [0] 
Processing eventDisplay.C...
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Error in <RootX11ErrorHandler>: GLXBadContext (TGLWidget XID: 67109776, XREQ: 152)
TGLWidget:	67109776
	TGVerticalFrame:	67109771
	TGLSAFrame:	67109760
	TGCompositeFrame:	67109759

and the usual window with the simulated geometry is empty.
Any idea to solve this problem?

Best regards

**Comment by ChristianTackeGSI** [comment]
Which OS, distribution, version are you using?

Do normal OpenGL programs work?
Like glxgears? (on Debian this is part of the "mesa-utils" package)

**Comment by dennisklein** [comment]
Thanks for your feedback :)
