### ISSUE TITLE
Running Hadrontherapy code

### ISSUE THREAD

**Issue by Mahnaz123456** [FairRootGroup/FairSoft#458]
I have successfully installed the Geant4 toolkit (Geant4 10.7 version). 
I have already copied the Hadrontherapy directory  and have also  built a Hadrontherapy-build directory in the same location. Would you please tell me how to run it in order to enable visualization and start the GUI?
I need to see the results in an  ASCII file. 
I appreciate your help in advance.

**Comment by ChristianTackeGSI** [comment]
What version of FairSoft are you using?
spack or legacy?
On which OS?

Can you show us more details?

**Comment by Mahnaz123456** [comment]
Dear ‪Dr. Christian Tacke, 

Thank you for your quick rreply. I have little experience working with Geant4 and I need to work on a project using Hadron therapy. I  asked Dr. John Allison by email about running Hadrontherapy and he responded that my question should go to the User Forum. I am not sure if I have sent my question in right place or not. Would you please guide me where I should send my question if it is needed. I appreciate your help in advance.

 By the way, the details of my system are as follows:

1) cmake version 3.22.1

2) Distributor ID:            Ubuntu

Description:     Ubuntu 18.04.6 LTS

Release:           18.04

Codename:      bionic

3) geant4-v11.0.0



 


----- Original Message -----

**Comment by MohammadAlTurany** [comment]
Wrong place! you should ask in the Geant4 Forum:
https://geant4-forum.web.cern.ch
