### ISSUE TITLE
[apr21p2] XROOTD compilation fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by PMunkes** [FairRootGroup/FairSoft#469]
Following the legacy build instructions for FairSoft apr21p2 on Ubuntu 22.04 LTS ends in a compilation error on XROOTD. This Ubuntu version ships with GCC 11.2, if that information is helpful.
Contents of `fairsoft_src_apr21p2_root6/build/Build/root/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-err.lof`
```
/home/philipp/Code/cbm/fairsoft_src_apr21p2_root6/build/Build/root/XROOTD-prefix/src/XROOTD/src/XrdCrypto/XrdCryptosslgsiAux.cc: In function ‘int XrdCryptosslX509SignProxyReq(XrdCryptoX509*, XrdCryptoRSA*, XrdCryptoX509Req*, XrdCryptoX509**)’:
/home/philipp/Code/cbm/fairsoft_src_apr21p2_root6/build/Build/root/XROOTD-prefix/src/XROOTD/src/XrdCrypto/XrdCryptosslgsiAux.cc:901:32: error: invalid conversion from ‘const rsa_st*’ to ‘RSA*’ {aka ‘rsa_st*’} [-fpermissive]
  901 |    RSA *kpi = EVP_PKEY_get0_RSA((EVP_PKEY *)(kcpi->Opaque()));
      |               ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                |
      |                                const rsa_st*
gmake[8]: *** [src/CMakeFiles/XrdCryptossl-4.dir/build.make:90: src/CMakeFiles/XrdCryptossl-4.dir/XrdCrypto/XrdCryptosslgsiAux.cc.o] Error 1
gmake[7]: *** [CMakeFiles/Makefile2:669: src/CMakeFiles/XrdCryptossl-4.dir/all] Error 2
gmake[6]: *** [Makefile:136: all] Error 2
```

**Comment by dennisklein** [comment]
I can confirm this issue. It was already reported to upstream ROOT, but it looks there is no solution so far: https://github.com/root-project/root/issues/10518

As a quick workaround I am testing now if disabling xrootd will help:
```diff
--- a/cmake/legacy.cmake
+++ b/cmake/legacy.cmake
@@ -368,7 +368,7 @@ if(PACKAGE_SET STREQUAL full)
       "-Dvdt=OFF"
       "-Dvmc=OFF"
       "-Dxml=ON"
-      "-Dxrootd=ON"
+      "-Dxrootd=OFF"
       "-Dx11=${root_x11}"
       ${python}
       ${root_builtin_glew}
```

**Comment by dennisklein** [comment]
Hm, I am encountering even more problems (Python related) with Geant4. I guess the conclusion for `apr21p2` will be similar to the ROOT issue: use newer release. For FairSoft this means use the apr22 release - this is tested on Ubuntu 22.04.

If you want to invest the time to backport the necessary patches for the old versions of ROOT and Geant4 in `apr21p2`, you are welcome to make a PR. From our side, it is unlikely, anyone will have the time to do this. Sry.

**Comment by dennisklein** [comment]
I tried disabling xrootd and g4py:

```diff
--- a/cmake/legacy.cmake
+++ b/cmake/legacy.cmake
@@ -317,7 +317,7 @@ if(PACKAGE_SET STREQUAL full)
       "-DGEANT4_USE_GDML=ON"
       "-DGEANT4_USE_OPENGL_X11=OFF"
       "-DGEANT4_USE_RAYTRACER_X11=OFF"
-      "-DGEANT4_USE_PYTHON=ON"
+      "-DGEANT4_USE_PYTHON=OFF"
       "-DGEANT4_INSTALL_DATA=ON"
       "-DGEANT4_BUILD_STORE_TRAJECTORY=OFF"
       "-DGEANT4_BUILD_VERBOSE_CODE=ON"
@@ -368,7 +368,7 @@ if(PACKAGE_SET STREQUAL full)
       "-Dvdt=OFF"
       "-Dvmc=OFF"
       "-Dxml=ON"
-      "-Dxrootd=ON"
+      "-Dxrootd=OFF"
       "-Dx11=${root_x11}"
       ${python}
       ${root_builtin_glew}
```

but this leads to a different Geant4 compilation issue with GCC 11...

**Comment by PMunkes** [comment]
Thanks for testing. I expect that it would be more beneficial to port CBMROOT forward to a newer FairSoft Version, so that's what I should be focussing on.
