### ISSUE TITLE
ssh is messed up by the crypto library in ${SIMPATH}/lib

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairSoft#471]
## Describe the bug
After source `thisroot.sh` in `${SIMPATH}/bin`, `/usr/bin/ssh` gives following error:
```shell
/usr/bin/ssh: symbol lookup error: /usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
```
This could be caused by `ssh` trying to link the crypto library `${SIMPATH}/lib/libcrypto.so.1.1` rather than the library from `/usr/lib64`. One could avoid such problem by placing the path `/usr/lib64` to the front of env variable `$LD_LIBRARY_PATH`.

Otherwise, both git and ssh are unusable.

## To Reproduce

1. install FairSoft via spack
2. source the file ${SIMPATH}/bin/thisroot.sh
3. try to use "git clone" anything.

## System information (please complete the following information):

Red Hat Enterprise Linux 8.6

## Suggestion:

Remove crypto libray from the $SIMPATH/lib
Or move all root libraries into a subfolder, just like previous versions of FairSoft.

**Comment by dennisklein** [comment]
> Remove crypto libray from the `$SIMPATH/lib`

You can achieve that
1. by passing `-e openssl` to the `spack view` command, or
2. by configuring spack to pick up your system openssl (devel pkg must be installed), see https://spack.readthedocs.io/en/latest/getting_started.html#openssl

In the future, we hope to not have to set `$LD_LIBRARY_PATH` at all (which is really the underlying bad practice), but fall back to baked `RUNPATH`s and setting [`$ROOT_LIBRARY_PATH`](https://github.com/root-project/root/blob/master/README/ReleaseNotes/v624/index.md#dynamic-path-root_library_path), but this work has not been finished.

**Comment by YanzhaoW** [comment]
> > Remove crypto libray from the `$SIMPATH/lib`
> 
> You can achieve that
> 
> 1. by passing `-e openssl` to the `spack view` command, or
> 2. by configuring spack to pick up your system openssl (devel pkg must be installed), see https://spack.readthedocs.io/en/latest/getting_started.html#openssl
> 
> In the future, we hope to not have to set `$LD_LIBRARY_PATH` at all (which is really the underlying bad practice), but fall back to baked `RUNPATH`s and setting [`$ROOT_LIBRARY_PATH`](https://github.com/root-project/root/blob/master/README/ReleaseNotes/v624/index.md#dynamic-path-root_library_path), but this work has not been finished.

Yes, adding `-e openssl` solve this problem. I would suggest adding this remark in the manual.
