### ISSUE TITLE
Boost

### ISSUE THREAD

**Issue by pasenov** [FairRootGroup/FairSoft#473]
Dear all, I am trying to install FairSoft on CENTOS 7. The sequence of commands is:

```
git clone -b apr22_patches https://github.com/FairRootGroup/FairSoft
sudo FairSoft/legacy/setup-centos-7.sh
mkdir build
cmake -S FairSoft -B build -C FairSoft/FairSoftConfig.cmake
cmake --build build
```

The output that I receive is:

```
[  0%] Creating directories for 'faircmakemodules'
[  0%] Performing download step (git clone) for 'faircmakemodules'
-- faircmakemodules download command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/faircmakemodules-download-*.log
[  0%] No patch step for 'faircmakemodules'
[  0%] Performing configure step for 'faircmakemodules'
-- faircmakemodules configure command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/faircmakemodules-configure-*.log
[  0%] Performing build step for 'faircmakemodules'
-- faircmakemodules build command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/faircmakemodules-build-*.log
[  0%] Performing install step for 'faircmakemodules'
-- faircmakemodules install command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/faircmakemodules-install-*.log
[  4%] Completed 'faircmakemodules'
[  4%] Built target faircmakemodules
[  4%] Creating directories for 'asio'
[  4%] Performing download step (git clone) for 'asio'
-- asio download command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/asio-download-*.log
[  8%] No patch step for 'asio'
[  8%] Performing configure step for 'asio'
-- asio configure command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/asio-configure-*.log
[  8%] Performing build step for 'asio'
-- asio build command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/asio-build-*.log
[  8%] Performing install step for 'asio'
-- asio install command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/asio-install-*.log
[  8%] Completed 'asio'
[  8%] Built target asio
[  8%] Creating directories for 'boost'
[  8%] Performing download step (download, verify and extract) for 'boost'
-- boost download command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/boost-download-*.log
[  8%] No patch step for 'boost'
[  8%] Performing configure step for 'boost'
-- boost configure command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/boost-configure-*.log
[ 13%] Performing build step for 'boost'
CMake Error at /home/pasenov/fair_install/FairSoft/build/Stamp/boost/boost-build-RelWithDebInfo.cmake:37 (message):
  Command failed: 1

   './b2' '--layout=system' 'cxxstd=17' 'link=shared' 'threading=multi' 'variant=release' 'visibility=hidden' 'pch=off' '--site-config=/home/pasenov/fair_install/FairSoft/build/site-config.jam' '-j 4'

  See also

    /home/pasenov/fair_install/FairSoft/build/Log/boost-build.log


-- Log output is:
...skipping to end...

common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_atomic-1.78.0/libboost_atomic-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/BoostDetectToolset-1.78.0.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/Boost-1.78.0/BoostConfig.cmake
boost-install.generate-cmake-config-version- bin.v2/tools/boost_install/BoostConfigVersion.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/Boost-1.78.0/BoostConfigVersion.cmake
boost-install.generate-cmake-config- bin.v2/libs/headers/build/stage/boost_headers-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_headers-1.78.0/boost_headers-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/headers/build/stage/boost_headers-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_headers-1.78.0/boost_headers-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_chrono.so.1.78.0
ln-UNIX /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_chrono.so
boost-install.generate-cmake-config- bin.v2/libs/chrono/build/stage/boost_chrono-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_chrono-1.78.0/boost_chrono-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/chrono/build/stage/boost_chrono-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_chrono-1.78.0/boost_chrono-config-version.cmake
boost-install.generate-cmake-variant- bin.v2/libs/chrono/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_chrono-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_chrono-1.78.0/libboost_chrono-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_container.so.1.78.0
ln-UNIX /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_container.so
boost-install.generate-cmake-config- bin.v2/libs/container/build/stage/boost_container-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_container-1.78.0/boost_container-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/container/build/stage/boost_container-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_container-1.78.0/boost_container-config-version.cmake
boost-install.generate-cmake-variant- bin.v2/libs/container/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_container-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_container-1.78.0/libboost_container-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_context.so.1.78.0
ln-UNIX /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_context.so
boost-install.generate-cmake-config- bin.v2/libs/context/build/stage/boost_context-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_context-1.78.0/boost_context-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/context/build/stage/boost_context-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_context-1.78.0/boost_context-config-version.cmake
boost-install.generate-cmake-variant- bin.v2/libs/context/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_context-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_context-1.78.0/libboost_context-variant-shared.cmake
...on 1000th target...
gcc.compile.c++ bin.v2/libs/wave/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/cpplexer/re2clex/cpp_re.o
boost-install.generate-cmake-config- bin.v2/libs/contract/build/stage/boost_contract-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_contract-1.78.0/boost_contract-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/contract/build/stage/boost_contract-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_contract-1.78.0/boost_contract-config-version.cmake
gcc.compile.c++ bin.v2/libs/coroutine/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/detail/coroutine_context.o
gcc.compile.c++ bin.v2/libs/coroutine/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/exceptions.o
gcc.compile.c++ bin.v2/libs/coroutine/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/posix/stack_traits.o
gcc.link.dll bin.v2/libs/coroutine/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_coroutine.so.1.78.0
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_coroutine.so.1.78.0
ln-UNIX /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_coroutine.so
boost-install.generate-cmake-config- bin.v2/libs/coroutine/build/stage/boost_coroutine-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_coroutine-1.78.0/boost_coroutine-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/coroutine/build/stage/boost_coroutine-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_coroutine-1.78.0/boost_coroutine-config-version.cmake
boost-install.generate-cmake-variant- bin.v2/libs/coroutine/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_coroutine-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_coroutine-1.78.0/libboost_coroutine-variant-shared.cmake
gcc.compile.c++ bin.v2/libs/date_time/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/gregorian/greg_month.o
gcc.link.dll bin.v2/libs/date_time/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_date_time.so.1.78.0
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_date_time.so.1.78.0
ln-UNIX /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_date_time.so
boost-install.generate-cmake-config- bin.v2/libs/date_time/build/stage/boost_date_time-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_date_time-1.78.0/boost_date_time-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/date_time/build/stage/boost_date_time-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_date_time-1.78.0/boost_date_time-config-version.cmake
boost-install.generate-cmake-variant- bin.v2/libs/date_time/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_date_time-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_date_time-1.78.0/libboost_date_time-variant-shared.cmake
gcc.compile.c++ bin.v2/libs/exception/build/gcc-7/release/cxxstd-17-iso/link-static/pch-off/threading-multi/visibility-hidden/clone_current_exception_non_intrusive.o
gcc.archive bin.v2/libs/exception/build/gcc-7/release/cxxstd-17-iso/link-static/pch-off/threading-multi/visibility-hidden/libboost_exception.a
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_exception.a
boost-install.generate-cmake-config- bin.v2/libs/exception/build/stage/boost_exception-config.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_exception-1.78.0/boost_exception-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/exception/build/stage/boost_exception-config-version.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_exception-1.78.0/boost_exception-config-version.cmake
gcc.compile.c++ bin.v2/libs/contract/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/contract.o
gcc.link.dll bin.v2/libs/contract/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_contract.so.1.78.0
boost-install.generate-cmake-variant- bin.v2/libs/contract/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/libboost_contract-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_contract.so.1.78.0
ln-UNIX /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_contract.so
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_contract-1.78.0/libboost_contract-variant-shared.cmake
gcc.compile.c++ bin.v2/libs/wave/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/instantiate_re2c_lexer.o
gcc.compile.c++ bin.v2/libs/wave/build/gcc-7/release/cxxstd-17-iso/pch-off/threading-multi/visibility-hidden/instantiate_re2c_lexer_str.o
gcc.link.dll bin.v2/libs/wave/build/gcc-7/release/cxxstd-17-iso/pch-off/threadapi-pthread/threading-multi/visibility-hidden/libboost_wave.so.1.78.0
boost-install.generate-cmake-variant- bin.v2/libs/wave/build/gcc-7/release/cxxstd-17-iso/pch-off/threadapi-pthread/threading-multi/visibility-hidden/libboost_wave-variant-shared.cmake
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_wave.so.1.78.0
ln-UNIX /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/libboost_wave.so
common.copy /home/pasenov/fair_install/FairSoft/build/Source/boost/stage/lib/cmake/boost_wave-1.78.0/libboost_wave-variant-shared.cmake
...failed updating 2 targets...
...skipped 10 targets...
...updated 1081 targets...

CMake Error at /home/pasenov/fair_install/FairSoft/build/Stamp/boost/boost-build-RelWithDebInfo.cmake:47 (message):
  Stopping after outputting logs.


gmake[2]: *** [CMakeFiles/boost.dir/build.make:85: Stamp/boost/boost-build] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:716: CMakeFiles/boost.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2
```

Is there any problem with boost? I reinstalled it and tried again, but I get the same message. 

Thank you very much in advance.

**Comment by fuhlig1** [comment]
Which compiler do you use? If you use the system compiler and not one newer one from the devtools you will not be able to compile FairSoft. The system compiler does not support C++17 which is required.

**Comment by pasenov** [comment]
[boost-build.log](https://github.com/FairRootGroup/FairSoft/files/9527577/boost-build.log)
[boost-configure.log](https://github.com/FairRootGroup/FairSoft/files/9527578/boost-configure.log)
[boost-download.log](https://github.com/FairRootGroup/FairSoft/files/9527579/boost-download.log)

Copying a .cmake file is not supported, so I copy-paste the text below:

===========================================================

cmake_minimum_required(VERSION 3.15)

set(command "./b2;--layout=system;cxxstd=17;link=shared;threading=multi;variant=release;visibility=hidden;pch=off;--site-config=/home/pasenov/fair_install/FairSoft/build/site-config.jam;-j 4")
set(log_merged "ON")
set(log_output_on_failure "ON")
set(stdout_log "/home/pasenov/fair_install/FairSoft/build/Log/boost-build.log")
set(stderr_log "/home/pasenov/fair_install/FairSoft/build/Log/boost-build.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
)
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /home/pasenov/fair_install/FairSoft/build/Log/boost-build-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  if(NOT "Unix Makefiles" MATCHES "Ninja")
    set(msg "boost build command succeeded.  See also /home/pasenov/fair_install/FairSoft/build/Log/boost-build-*.log")
    message(STATUS "${msg}")
  endif()
endif()

===========================================================

I have installed devtoolset and I did:

scl enable devtoolset-7 bash

After gcc --version, I get:

gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

Should I change anything?

**Comment by dennisklein** [comment]
Your logs show two instances of the following error:
```
./boost/asio/detail/memory.hpp: In function ‘void* boost::asio::aligned_new(std::size_t, std::size_t)’:
./boost/asio/detail/memory.hpp:88:20: error: ‘aligned_alloc’ is not a member of ‘std’
   void* ptr = std::aligned_alloc(align, size);
                    ^~~~~~~~~~~~~
./boost/asio/detail/memory.hpp:88:20: note: suggested alternative: ‘aligned_union’
   void* ptr = std::aligned_alloc(align, size);
                    ^~~~~~~~~~~~~
                    aligned_union
```

This error is known upstream: https://github.com/chriskohlhoff/asio/issues/955. However, we have tested FairSoft `apr22` on CentOS 7 with [`devtoolset-11`](https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/11/html-single/user_guide/index#sect-GCC-C-Compile), see https://github.com/FairRootGroup/FairSoft/blob/apr22_patches/legacy/README.md#tested-systems.

> Should I change anything?

I recommend to use `devtoolset-11` as it contains GCC version 11 (released 2021) which is much newer than the GCC version 7 (released 2018) you have used. (Even if you fix the error above, I expect you will encounter more problems down the line because [GCC version 7's standard library is not fully featured C++17](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017) which FairSoft `apr22` requires.) Closing, feel free to re-open if there are still questions!

**Comment by pasenov** [comment]
[root-build.log](https://github.com/FairRootGroup/FairSoft/files/9535449/root-build.log)

**Comment by dennisklein** [comment]
Can you also share `root-configure.log`? Also please share the output of the shell command `rpm -qf /usr/include/nlohmann/json.hpp`.

**Comment by pasenov** [comment]
[root-configure.log](https://github.com/FairRootGroup/FairSoft/files/9550369/root-configure.log)

[pasenov@cds01 FairSoft]$ rpm -qf /usr/include/nlohmann/json.hpp
json-devel-3.6.1-2.el7.x86_64

**Comment by pasenov** [comment]
So, I should save the above commands in a new file, let's say patch1.patch and save it here:

/home/pasenov/fair_install/FairSoft/FairSoft/patches/dds

And then rerun the previous command? Did I miss anything?

**Comment by pasenov** [comment]
[pasenov@cds01 FairSoft]$ cmake --build build
[  4%] Built target faircmakemodules
[  8%] Built target asio
[ 13%] Built target boost
[ 17%] Built target fmt
[ 26%] Built target dds
[ 30%] Built target fairlogger
[ 34%] Built target zeromq
[ 39%] Built target flatbuffers
[ 43%] Built target fairmq
[ 47%] Built target pythia6
[ 52%] Built target hepmc
[ 56%] Built target vc
[ 60%] Built target clhep
[ 65%] Built target pythia8
[ 69%] Built target geant4
[ 69%] Performing build step for 'root'
CMake Error at /home/pasenov/fair_install/FairSoft/build/Stamp/root/root-build-RelWithDebInfo.cmake:37 (message):
  Command failed: 2

   '/opt/rh/devtoolset-11/root/usr/bin/gmake'

  See also

    /home/pasenov/fair_install/FairSoft/build/Log/root-build.log


-- Log output is:
...skipping to end...
ld/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_vector.h:1962:5: note:                 ‘template<class _Tp, class _Alloc> void std::swap(std::vector<_Tp, _Alloc>&, std::vector<_Tp, _Alloc>&)’
 1962 |     swap(vector<_Tp, _Alloc>& __x, vector<_Tp, _Alloc>& __y)
      |     ^~~~
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:55,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/meta/inc/TSchemaHelper.h:17,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/meta/inc/TGenericClassInfo.h:21,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/base/inc/Rtypes.h:191,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/gui/inc/GuiTypes.h:22,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveTypes.hxx:16,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:6493:5: note:                 ‘template<class _CharT, class _Traits, class _Alloc> void std::swap(std::basic_string<_CharT, _Traits, _Allocator>&, std::basic_string<_CharT, _Traits, _Allocator>&)’
 6493 |     swap(basic_string<_CharT, _Traits, _Alloc>& __lhs,
      |     ^~~~
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_algobase.h:64,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/char_traits.h:39,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:40,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/meta/inc/TSchemaHelper.h:17,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/meta/inc/TGenericClassInfo.h:21,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/base/inc/Rtypes.h:191,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/gui/inc/GuiTypes.h:22,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveTypes.hxx:16,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_pair.h:541:5: note:                 ‘template<class _T1, class _T2> typename std::enable_if<(! std::__and_<std::__is_swappable<_T1>, std::__is_swappable<_T2> >::value)>::type std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)’
  541 |     swap(pair<_T1, _T2>&, pair<_T1, _T2>&) = delete;
      |     ^~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_pair.h:533:5: note:                 ‘template<class _T1, class _T2> typename std::enable_if<std::__and_<std::__is_swappable<_T1>, std::__is_swappable<_T2> >::value>::type std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)’
  533 |     swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
      |     ^~~~
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/atomic_base.h:38,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/atomic:41,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/base/inc/Rtypes.h:35,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/core/gui/inc/GuiTypes.h:22,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveTypes.hxx:16,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/move.h:220:5: note:                 ‘template<class _Tp, long unsigned int _Nm> std::__enable_if_t<std::__is_swappable<_Tp>::value> std::swap(_Tp (&)[_Nm], _Tp (&)[_Nm])’
  220 |     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
      |     ^~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/move.h:196:5: note:                 ‘template<class _Tp> std::_Require<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> > std::swap(_Tp&, _Tp&)’
  196 |     swap(_Tp& __a, _Tp& __b)
      |     ^~~~
In file included from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:18:
/usr/include/nlohmann/json.hpp:20793:69: error: return type ‘using json = class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’ {aka ‘class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} is incomplete
20793 | inline nlohmann::json operator "" _json(const char* s, std::size_t n)
      |                                                                     ^
/usr/include/nlohmann/json.hpp: In function ‘void operator""_json(const char*, std::size_t)’:
/usr/include/nlohmann/json.hpp:20795:28: error: incomplete type ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} used in nested name specifier
20795 |     return nlohmann::json::parse(s, s + n);
      |                            ^~~~~
/usr/include/nlohmann/json.hpp: At global scope:
/usr/include/nlohmann/json.hpp:20811:24: error: invalid use of incomplete type ‘using json = class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’ {aka ‘class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’}
20811 | inline nlohmann::json::json_pointer operator "" _json_pointer(const char* s, std::size_t n)
      |                        ^~~~~~~~~~~~
In file included from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:33:7: note: declaration of ‘using json = class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’ {aka ‘class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’}
   33 | class basic_json;
      |       ^~~~~~~~~~
/home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx: In member function ‘virtual Int_t ROOT::Experimental::REveBox::WriteCoreJson(nlohmann::json&, Int_t)’:
/home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:106:5: error: no match for ‘operator[]’ (operand types are ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} and ‘const char [11]’)
  106 |    j["fMainColor"] = GetFillColor();
      |     ^
/home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:107:5: error: no match for ‘operator[]’ (operand types are ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} and ‘const char [11]’)
  107 |    j["fLineColor"] = GetLineColor();
      |     ^
/home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx: In member function ‘virtual Int_t ROOT::Experimental::REveBoxProjected::WriteCoreJson(nlohmann::json&, Int_t)’:
/home/pasenov/fair_install/FairSoft/build/Source/root/graf3d/eve7/src/REveBox.cxx:283:5: error: no match for ‘operator[]’ (operand types are ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} and ‘const char [10]’)
  283 |    j["fBreakIdx"] = fBreakIdx;
      |     ^
gmake[5]: *** [graf3d/eve7/CMakeFiles/ROOTEve.dir/build.make:230: graf3d/eve7/CMakeFiles/ROOTEve.dir/src/REveBox.cxx.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:31538: graf3d/eve7/CMakeFiles/ROOTEve.dir/all] Error 2
gmake[3]: *** [Makefile:156: all] Error 2

CMake Error at /home/pasenov/fair_install/FairSoft/build/Stamp/root/root-build-RelWithDebInfo.cmake:47 (message):
  Stopping after outputting logs.


gmake[2]: *** [CMakeFiles/root.dir/build.make:85: Stamp/root/root-build] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:3442: CMakeFiles/root.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2

================================================================================


I fear that I have missed some important steps in applying the patch correctly.

**Comment by dennisklein** [comment]
> So, I should save the above commands in a new file, let's say patch1.patch and save it here:

Sry, no, I meant you to modify the file `/home/pasenov/fair_install/FairSoft/FairSoft/cmake/legacy.cmake` and add the ROOT build option `"-Dbuiltin_nlohmannjson=ON"`.

**Comment by pasenov** [comment]
FairSoft was finally successfully installed on my computer. The last suggestion really helped (though my legacy.cmake file didn't have exactly the same contents as shown above).

@dennisklein thank you very much for the assistance!

**Comment by dennisklein** [comment]
I prepared a commit 7da32389bbc02332dc2651be8d13952bbdc6c4f8 that is likely to make it into our `dev` branch and into the next release (with the option to backport it to older releases if requested).
