### ISSUE TITLE
Installation from source on macOS 12.6 with Xcode 14.0

### ISSUE THREAD

**Issue by kresan** [FairRootGroup/FairSoft#476]
/usr/bin/patch from macOS distribution does not recognise --merge option. Build fails.

Was able to fix this by installing `gpatch` with `brew` and re-running cmake.

@dennisklein Should we add `gpatch` to `legacy/setup-macos.sh` ?

**Comment by fuhlig1** [comment]
Hi Dima,

gpatch is alreday in the setup-macos.sh  script.

Ciao

Florian

Am 21.09.2022 um 02:35 schrieb Dmytro Kresan ***@***.******@***.***>>:



/usr/bin/patch from macOS distribution does not recognise --merge option. Build fails.

Was able to fix this by installing gpatch with brew and re-running cmake.

@dennisklein<https://github.com/dennisklein> Should we add gpatch to legacy/setup-macos.sh ?

**Comment by kresan** [comment]
Yes, indeed. Later I have realised that I did not run the setup script on that machine. Closing.
