### ISSUE TITLE
Device does not terminate properly

### ISSUE THREAD

**Issue by matthiasrichter** [FairRootGroup/FairSoft#49]
Just made an observation when playing with the examples in examples/MQ/6-multiple-channels

If just one device is started like e.g. 

```
bin/ex6-sink --id sink1 --mq-config config/ex6-multiple-channels.json
```

it does not terminate properly on CTRL-C or 'q'. The only way is to use kill command and process id.

Happens for the sampler in similar way. Both devices terminate properly if they communication has been established and data is sent and received.

**Comment by rbx** [comment]
I've tracked the issue down last week, it will be fixed with the next PR.

**Comment by matthiasrichter** [comment]
very good!
