### ISSUE TITLE
Problems to install FairSoft on CENTOS 7

### ISSUE THREAD

**Issue by jose-luis-rs** [FairRootGroup/FairSoft#493]
I am trying to install FairSoft on CentOS Linux release 7.9.2009 with gcc-11:
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)

The sequence of commands was:

git clone -b apr22_patches https://github.com/FairRootGroup/FairSoft
sudo FairSoft/legacy/setup-centos-7.sh
mkdir build
cmake -S FairSoft -B build -C FairSoft/FairSoftConfig.cmake
cmake --build build

and below you can find the error:

**cmake -S FairSoft -B build -C FairSoft/FairSoftConfig.cmake**

loading initial cache file FairSoft/FairSoftConfig.cmake
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
-- The Fortran compiler identification is GNU 11.2.1
-- Check for working C compiler: /opt/rh/devtoolset-11/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-11/root/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done 
-- Check for working CXX compiler: /opt/rh/devtoolset-11/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-11/root/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /opt/rh/devtoolset-11/root/usr/bin/gfortran
-- Check for working Fortran compiler: /opt/rh/devtoolset-11/root/usr/bin/gfortran - works
-- Detecting Fortran compiler ABI info 
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/rh/devtoolset-11/root/usr/bin/gfortran supports Fortran 90
-- Checking whether /opt/rh/devtoolset-11/root/usr/bin/gfortran supports Fortran 90 - yes
-- Found Git: /usr/bin/git (found version "1.8.3.1")
-- Found Patch: /usr/bin/patch
-- Found UnixCommands: /usr/bin/bash   
-- NCPUS: 40 (from ProcessorCount())   
-- Found Python: /usr/bin/python3.6 (found suitable version "3.6.8", minimum required is "3") found components: Interpreter Development
--
--   CXX STANDARD       C++17 (change with -DCMAKE_CXX_STANDARD=17)
--
--   BUILD TYPE         RelWithDebInfo (change with -DCMAKE_BUILD_TYPE=...)
--
--   PACKAGE SET        full (change with -DPACKAGE_SET=...)

--   PACKAGE              VERSION         OPTION
--   asio                 1.19.1
--   boost                1.78.0
--   clhep                2.4.5.1
--   dds                  3.6
--   faircmakemodules     1.0.0
--   fairlogger           1.11.0
--   fairmq               1.4.50
--   flatbuffers          1.12.0
--   fmt                  8.1.1
--   geant3               4-0_fairsoft
--   geant4               11.0.1          single-threaded (change with -DGEANT4MT=ON)
--   geant4_vmc           6-1
--   hepmc                2.06.11
--   pythia6              428-alice1
--   pythia8              8306
--   root                 6.26.02
--   vc                   1.4.2
--   vgm                  5-0
--   vmc                  2-0
--   zeromq               4.3.4
--
--   SOURCE CACHE       using upstream URLs (generate cache by building target 'source-cache' and pass via -DSOURCE_CACHE=...)

-- Configuring done
-- Generating done
-- Build files have been written to: /xxxx/build

**cmake --build build**

Scanning dependencies of target zeromq
[  0%] Creating directories for 'zeromq'
[  0%] Performing download step (git clone) for 'zeromq'
-- zeromq download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/zeromq-download-*.log
[  0%] No patch step for 'zeromq'
[  0%] Skipping update step for 'zeromq'
[  4%] Performing configure step for 'zeromq'
-- zeromq configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/zeromq-configure-*.log
[  4%] Performing build step for 'zeromq'
-- zeromq build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/zeromq-build-*.log
[  4%] Performing install step for 'zeromq'
-- zeromq install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/zeromq-install-*.log
[  4%] Completed 'zeromq'
[  4%] Built target zeromq
[  9%] Creating directories for 'boost'
[  9%] Performing download step (download, verify and extract) for 'boost'
-- boost download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/boost-download-*.log
[  9%] No patch step for 'boost'
[  9%] No skip-update step for 'boost'
[  9%] Performing configure step for 'boost'
-- boost configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/boost-configure-*.log
[  9%] Performing build step for 'boost'
-- boost build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/boost-build-*.log
[  9%] Performing install step for 'boost'
-- boost install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/boost-install-*.log
[  9%] Completed 'boost'
[  9%] Built target boost
Scanning dependencies of target clhep
[  9%] Creating directories for 'clhep'
[  9%] Performing download step (download, verify and extract) for 'clhep'
-- clhep download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/clhep-download-*.log
[  9%] Performing move_dir step for 'clhep'
-- clhep move_dir command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/clhep-move_dir-*.log
[ 13%] No patch step for 'clhep'
[ 13%] No skip-update step for 'clhep'
[ 13%] Performing configure step for 'clhep'
-- clhep configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/clhep-configure-*.log
[ 13%] Performing build step for 'clhep'
-- clhep build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/clhep-build-*.log
[ 13%] Performing install step for 'clhep'
-- clhep install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/clhep-install-*.log
[ 13%] Completed 'clhep'
[ 13%] Built target clhep
Scanning dependencies of target geant4
[ 13%] Creating directories for 'geant4'
[ 13%] Performing download step (download, verify and extract) for 'geant4'
-- geant4 download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/geant4-download-*.log
[ 13%] No patch step for 'geant4'
[ 13%] No skip-update step for 'geant4'
[ 13%] Performing configure step for 'geant4'
-- geant4 configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/geant4-configure-*.log
[ 13%] Performing build step for 'geant4'
-- geant4 build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/geant4-build-*.log
[ 18%] Performing install step for 'geant4'
-- geant4 install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/geant4-install-*.log
[ 18%] Completed 'geant4'
[ 18%] Built target geant4
 18%] Creating directories for 'faircmakemodules'
[ 18%] Performing download step (git clone) for 'faircmakemodules'
-- faircmakemodules download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/faircmakemodules-download-*.log
[ 18%] No patch step for 'faircmakemodules'
[ 18%] Skipping update step for 'faircmakemodules'
[ 18%] Performing configure step for 'faircmakemodules'
-- faircmakemodules configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/faircmakemodules-configure-*.log
[ 18%] Performing build step for 'faircmakemodules'
-- faircmakemodules build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/faircmakemodules-build-*.log
[ 22%] Performing install step for 'faircmakemodules'
-- faircmakemodules install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/faircmakemodules-install-*.log
[ 22%] Completed 'faircmakemodules'
[ 22%] Built target faircmakemodules 
Scanning dependencies of target vc
[ 22%] Creating directories for 'vc'
[ 22%] Performing download step (download, verify and extract) for 'vc'
-- vc download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/vc-download-*.log
[ 22%] No patch step for 'vc'
[ 22%] No skip-update step for 'vc'
[ 22%] Performing configure step for 'vc'
-- vc configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/vc-configure-*.log
[ 27%] Performing build step for 'vc'
-- vc build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/vc-build-*.log
[ 27%] Performing install step for 'vc'
-- vc install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/vc-install-*.log
[ 27%] Completed 'vc'
[ 27%] Built target vc
Scanning dependencies of target fmt
[ 27%] Creating directories for 'fmt'
[ 27%] Performing download step (download, verify and extract) for 'fmt'
-- fmt download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/fmt-download-*.log
[ 31%] No patch step for 'fmt'
[ 31%] No skip-update step for 'fmt'
[ 31%] Performing configure step for 'fmt'
-- fmt configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/fmt-configure-*.log
[ 31%] Performing build step for 'fmt'
-- fmt build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/fmt-build-*.log
[ 31%] Completed 'fmt'
[ 31%] Built target fmt
Scanning dependencies of target fairlogger
[ 31%] Creating directories for 'fairlogger'
[ 36%] Performing download step (git clone) for 'fairlogger'
-- fairlogger download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/fairlogger-download-*.log
[ 36%] No patch step for 'fairlogger'
[ 36%] Skipping update step for 'fairlogger'
[ 36%] Performing configure step for 'fairlogger'
-- fairlogger configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/fairlogger-configure-*.log
[ 36%] Performing build step for 'fairlogger'
-- fairlogger build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/fairlogger-build-*.log
[ 36%] Performing install step for 'fairlogger'
-- fairlogger install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/fairlogger-install-*.log
[ 36%] Completed 'fairlogger'
[ 36%] Built target fairlogger
Scanning dependencies of target asio
[ 36%] Creating directories for 'asio'
[ 36%] Performing download step (git clone) for 'asio'
-- asio download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/asio-download-*.log
[ 36%] No patch step for 'asio'
[ 40%] Skipping update step for 'asio'
[ 40%] Performing configure step for 'asio'
-- asio configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/asio-configure-*.log
[ 40%] Performing build step for 'asio'
-- asio build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/asio-build-*.log
[ 40%] Performing install step for 'asio'
-- asio install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/asio-install-*.log
[ 40%] Completed 'asio'
[ 40%] Built target asio
Scanning dependencies of target flatbuffers
[ 45%] Creating directories for 'flatbuffers'
[ 45%] Performing download step (git clone) for 'flatbuffers'
-- flatbuffers download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/flatbuffers-download-*.log
[ 45%] Performing patch step for 'flatbuffers'
-- flatbuffers patch command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/flatbuffers-patch-*.log
[ 45%] Skipping update step for 'flatbuffers'
[ 45%] Performing configure step for 'flatbuffers'
-- flatbuffers configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/flatbuffers-configure-*.log
[ 45%] Performing build step for 'flatbuffers'
-- flatbuffers build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/flatbuffers-build-*.log
[ 45%] Performing install step for 'flatbuffers'
-- flatbuffers install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/flatbuffers-install-*.log
[ 45%] Completed 'flatbuffers'
[ 45%] Built target flatbuffers
[ 45%] Creating directories for 'hepmc'
[ 45%] Performing download step (download, verify and extract) for 'hepmc'
-- hepmc download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/hepmc-download-*.log
[ 45%] No patch step for 'hepmc'
[ 45%] No skip-update step for 'hepmc'
[ 45%] Performing configure step for 'hepmc'
-- hepmc configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/hepmc-configure-*.log
[ 50%] Performing build step for 'hepmc'
-- hepmc build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/hepmc-build-*.log
[ 50%] Performing install step for 'hepmc'
-- hepmc install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/hepmc-install-*.log
[ 50%] Completed 'hepmc'
[ 50%] Built target hepmc
Scanning dependencies of target pythia8
[ 54%] Creating directories for 'pythia8'
[ 54%] Performing download step (download, verify and extract) for 'pythia8'
-- pythia8 download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia8-download-*.log
[ 54%] No patch step for 'pythia8'
[ 54%] No skip-update step for 'pythia8'
[ 54%] Performing configure step for 'pythia8'
-- pythia8 configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia8-configure-*.log
[ 54%] Performing build step for 'pythia8'
-- pythia8 build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia8-build-*.log
[ 54%] Performing install step for 'pythia8'
-- pythia8 install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia8-install-*.log
[ 54%] Completed 'pythia8'
[ 54%] Built target pythia8
Scanning dependencies of target pythia6
[ 54%] Creating directories for 'pythia6'
[ 54%] Performing download step (download, verify and extract) for 'pythia6'
-- pythia6 download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia6-download-*.log
[ 54%] Performing patch step for 'pythia6'
-- pythia6 patch command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia6-patch-*.log
[ 54%] No skip-update step for 'pythia6'
[ 54%] Performing configure step for 'pythia6'
-- pythia6 configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia6-configure-*.log
[ 54%] Performing build step for 'pythia6'
-- pythia6 build command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia6-build-*.log
[ 54%] Performing install step for 'pythia6'
-- pythia6 install command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/pythia6-install-*.log
[ 59%] Completed 'pythia6'
[ 59%] Built target pythia6
Scanning dependencies of target root
[ 59%] Creating directories for 'root'
[ 59%] Performing download step (git clone) for 'root'
-- root download command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/root-download-*.log
[ 59%] Performing patch step for 'root'
-- root patch command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/root-patch-*.log
[ 59%] Skipping update step for 'root'
[ 63%] Performing configure step for 'root'
-- root configure command succeeded.  See also /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/root-configure-*.log
[ 63%] Performing build step for 'root'
CMake Error at /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Stamp/root/root-build-RelWithDebInfo.cmake:37 (message):
  Command failed: 2

   '/opt/rh/devtoolset-11/root/usr/bin/gmake'

  See also

    /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Log/root-build.log

-- Log output is:
...skipping to end...
PR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_vector.h:1962:5: note:                 ‘template<class _Tp, class _Alloc> void std::swap(std::vector<_Tp, _Alloc>&, std::vector<_Tp, _Alloc>&)’
 1962 |     swap(vector<_Tp, _Alloc>& __x, vector<_Tp, _Alloc>& __y)
      |     ^~~~
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:55,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/meta/inc/TSchemaHelper.h:17,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/meta/inc/TGenericClassInfo.h:21,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/base/inc/Rtypes.h:191,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/gui/inc/GuiTypes.h:22,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveTypes.hxx:16,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:6493:5: note:                 ‘template<class _CharT, class _Traits, class _Alloc> void std::swap(std::basic_string<_CharT, _Traits, _Allocator>&, std::basic_string<_CharT, _Traits, _Allocator>&)’
 6493 |     swap(basic_string<_CharT, _Traits, _Alloc>& __lhs,
      |     ^~~~
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_algobase.h:64,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/char_traits.h:39,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:40,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/meta/inc/TSchemaHelper.h:17,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/meta/inc/TGenericClassInfo.h:21,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/base/inc/Rtypes.h:191,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/gui/inc/GuiTypes.h:22,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveTypes.hxx:16,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_pair.h:541:5: note:                 ‘template<class _T1, class _T2> typename std::enable_if<(! std::__and_<std::__is_swappable<_T1>, std::__is_swappable<_T2> >::value)>::type std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)’
  541 |     swap(pair<_T1, _T2>&, pair<_T1, _T2>&) = delete;
      |     ^~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/stl_pair.h:533:5: note:                 ‘template<class _T1, class _T2> typename std::enable_if<std::__and_<std::__is_swappable<_T1>, std::__is_swappable<_T2> >::value>::type std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)’
  533 |     swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
      |     ^~~~
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/atomic_base.h:38,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/atomic:41,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/base/inc/Rtypes.h:35,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/core/gui/inc/GuiTypes.h:22,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveTypes.hxx:16,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/move.h:220:5: note:                 ‘template<class _Tp, long unsigned int _Nm> std::__enable_if_t<std::__is_swappable<_Tp>::value> std::swap(_Tp (&)[_Nm], _Tp (&)[_Nm])’
  220 |     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
      |     ^~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/move.h:196:5: note:                 ‘template<class _Tp> std::_Require<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> > std::swap(_Tp&, _Tp&)’
  196 |     swap(_Tp& __a, _Tp& __b)
In file included from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:18:
/usr/include/nlohmann/json.hpp:20793:69: error: return type ‘using json = class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’ {aka ‘class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} is incomplete
20793 | inline nlohmann::json operator "" _json(const char* s, std::size_t n)
      |                                                                     ^
/usr/include/nlohmann/json.hpp: In function ‘void operator""_json(const char*, std::size_t)’:
/usr/include/nlohmann/json.hpp:20795:28: error: incomplete type ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} used in nested name specifier
20795 |     return nlohmann::json::parse(s, s + n);
      |                            ^~~~~
/usr/include/nlohmann/json.hpp: At global scope:
/usr/include/nlohmann/json.hpp:20811:24: error: invalid use of incomplete type ‘using json = class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’ {aka ‘class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’}
20811 | inline nlohmann::json::json_pointer operator "" _json_pointer(const char* s, std::size_t n)
      |                        ^~~~~~~~~~~~
In file included from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveShape.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveBox.hxx:15,
                 from /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:12:
/opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/inc/ROOT/REveElement.hxx:33:7: note: declaration of ‘using json = class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’ {aka ‘class nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’}
   33 | class basic_json;
      |       ^~~~~~~~~~
/opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx: In member function ‘virtual Int_t ROOT::Experimental::REveBox::WriteCoreJson(nlohmann::json&, Int_t)’:
/opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:106:5: error: no match for ‘operator[]’ (operand types are ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} and ‘const char [11]’)
  106 |    j["fMainColor"] = GetFillColor();
      |     ^
/opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:107:5: error: no match for ‘operator[]’ (operand types are ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} and ‘const char [11]’)
  107 |    j["fLineColor"] = GetLineColor();
      |     ^
/opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx: In member function ‘virtual Int_t ROOT::Experimental::REveBoxProjected::WriteCoreJson(nlohmann::json&, Int_t)’:
/opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Source/root/graf3d/eve7/src/REveBox.cxx:283:5: error: no match for ‘operator[]’ (operand types are ‘nlohmann::json’ {aka ‘nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char> >’} and ‘const char [10]’)
  283 |    j["fBreakIdx"] = fBreakIdx;
gmake[5]: *** [graf3d/eve7/CMakeFiles/ROOTEve.dir/build.make:226: graf3d/eve7/CMakeFiles/ROOTEve.dir/src/REveBox.cxx.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:33537: graf3d/eve7/CMakeFiles/ROOTEve.dir/all] Error 2
gmake[3]: *** [Makefile:172: all] Error 2

CMake Error at /opt/expSoftware/NUCLEAR/FAIRSOFTAPR22/build/Stamp/root/root-build-RelWithDebInfo.cmake:47 (message):
  Stopping after outputting logs.

gmake[2]: *** [CMakeFiles/root.dir/build.make:131: Stamp/root/root-build] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:5249: CMakeFiles/root.dir/all] Error 2
gmake: *** [Makefile:115: all] Error 2

Any idea to solve this problem?

Thanks in advance

**Comment by dennisklein** [comment]
Please add the following line to your `cmake/legacy.cmake` file and rerun the build command: https://github.com/FairRootGroup/FairSoft/commit/7da32389bbc02332dc2651be8d13952bbdc6c4f8 (The system json library got updated in centos7 in a non-compatible way with the ROOT version in FairSoft apr22 it seems)

**Comment by jose-luis-rs** [comment]
Thanks, it works!

**Comment by jose-luis-rs** [comment]
The problem now is that I cannot install the gtest library from FairRoot, any idea to solve this problem?
https://github.com/FairRootGroup/FairRoot/issues/1335

**Comment by dennisklein** [comment]
I'll reopen as a reminder to add the above patch you confirmed to be working (thx for that!) to the repo. Will close it once its done.

**Comment by dennisklein** [comment]
Centos7 no longer a supported platform.
