### ISSUE TITLE
FairSoft apr22 or nov22 lxplus8

### ISSUE THREAD

**Issue by EugeniaSpedicato** [FairRootGroup/FairSoft#495]
Dear experts,

I was wondering if it was possible to have one of the newest release of FairSoft on cvmfs on lxplus8 (apr22 or nov22), as I see that there exists just the 2021 ones and it would be great for my studies to have a more updated geant4 version. 
I hope that this won't create many problems for you, let me know if it is possible.

Thank you so much!

**Comment by fuhlig1** [comment]
What is lxplus8?

**Comment by EugeniaSpedicato** [comment]
The cern environment where FairSoft can be reached:
path
/cvmfs/fairsoft.gsi.de/centos8/fairsoft/apr21p2

Maybe it is just the release you have set in the cvmfs with centos8, btw which was done also to be compatible with lxplus

**Comment by fuhlig1** [comment]
We probably can install a newer version with our centos8 environment. I am not sure if the installation will work with your centos8 environment at CERN.

**Comment by EugeniaSpedicato** [comment]
The previous versions worked, so I think it should be fine. Btw if this won't take too much time for you, that would be useful to try, thanks.

**Comment by fuhlig1** [comment]
@EugeniaSpedicato,

I have now installed the latest FairSoft release nov22p1 at

/cvmfs/fairsoft.gsi.de/centos8/fairsoft/nov22p1

Please try if this installation works with your environment.

**Comment by EugeniaSpedicato** [comment]
Great thanks! I'll try it as soon as possible.

**Comment by fuhlig1** [comment]
@EugeniaSpedicato,

did you try the cvmfs installation?

**Comment by EugeniaSpedicato** [comment]
Yes sorry. It worked (even if cern has changed from centos8 to alma)
I close the issue
