### ISSUE TITLE
ZeroMQ is built without Draft API

### ISSUE THREAD

**Issue by fweig** [FairRootGroup/FairSoft#496]
Is there a reason why ZeroMQ is built without the Draft API?
https://github.com/FairRootGroup/FairSoft/blob/fae837212b17659c834ce928d5b0a58d4d15be0d/cmake/legacy.cmake#L207

This API is required by FlesNet, so at the moment FlesNet doesn't work with ZeroMQ shipped byFairSoft. It would be nice to enable this by default, so there's no need to instruct FlesNet to build it's own version of ZeroMQ.

**Comment by dennisklein** [comment]
> Is there a reason why ZeroMQ is built without the Draft API?

There may have been a problem with GnuTLS, see https://github.com/zeromq/libzmq/blob/4097855ddaaa65ed7b5e8cb86d143842a594eebd/CMakeLists.txt#L197. In case this reappears and it turns out to be a blocker, do you need `WITH_TLS` as well?

**Comment by fweig** [comment]
If it rides the release in April, that's great! No need for backports. I'll just stick to my workaround in the meantime.

**Comment by fweig** [comment]
> There may have been a problem with GnuTLS, see https://github.com/zeromq/libzmq/blob/4097855ddaaa65ed7b5e8cb86d143842a594eebd/CMakeLists.txt#L197. In case this reappears and it turns out to be a blocker, do you need WITH_TLS as well?

FlesNet uses [this Patch](https://github.com/cbm-fles/flesnet/blob/master/fix_gnutls_macosx_v4.3.4.patch) to fix compilation with TLS. That should be applicable here as well? I'm _probably_ fine without TLS, but would be nice if we could just keep it enabled.

**Comment by dennisklein** [comment]
Implemented via ea320650cb5ecab695f22113e182b08f8e38deed and 6f1ce621c8c23430ba0a1fcc7fa3a5c614f96432 (ZeroMQ 4.3.5 fixes the GnuTLS issue). Sry for the delay, next release will hopefully happen in January 2024.
