### ISSUE TITLE
cvmfs: please put build on cvmfs

### ISSUE THREAD

**Issue by klenze** [FairRootGroup/FairSoft#498]
Dear FairSoft devs,
when debugging, it is often helpful to have the build directories (with the sources) available, so one can quickly check what e.g. a ROOT or GEANT4 method does internally. 
Unfortunately, the build path /home/uhlig/containers/home/debian10/software/fairsoft/nov22p1/build is neither on the cvmfs nor accessible from GSI pool machines. 

Do you think you could build in a /cvmfs/ location for the next release?

This also applies to FairRoot. 

Cheers,
   Philipp

**Comment by dennisklein** [comment]
Imho, build and source directories (all projects are open source after all) should not be shipped, however, if @fuhlig1 or someone else wants to support it, I won't stop them :)

**Comment by fuhlig1** [comment]
The build and source directories will not be installed on CVMFS. If debugging is needed this should not be done on the compute cluster.
In such cases please use a dedicated installation which can be put to /lustre.

**Comment by ChristianTackeGSI** [comment]
> which can be put to /lustre.

… or in the future on `/scratch` (still in testing / beta).
