### ISSUE TITLE
MacOS: Compilation failure after upgrading to 13.3.1 

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairSoft#499]
Hi,

I'm not sure whether anyone else have noticed the compilation failure from root installation when upgrading macOS system to 13.3.1. I looked it up in internet and found multiple sources about this failure:

https://root-forum.cern.ch/t/building-failed-after-upgrade-to-mac-os-13-3-1/54420

https://github.com/root-project/root/issues/12644

The solution could be upgrading root to 6.28.02.

Currently in my case FairSoft cannot be installed in MacOS 13.3.1.

**Comment by dennisklein** [comment]
Hi, yes this is known. There is a new FairSoft release in the shortterm (maybe end of april or may), which will ship the latest root.

In the meantime, if you feel like it, have a look a the file `cmake/legacy.cmake`. It describes all the packages, versions, and configurations. If you are lucky and there were no other major changes between root 6.26 and 6.28, you may be able to make it work again on your system by just updating the root package.

In any case, if you try updating root and you find any related issues, you are welcome to open an issue, so we can track and resolve everything relevant :)

**Comment by YanzhaoW** [comment]
I see, thanks. Is there any plan to fix this issue on homebrew?

**Comment by dennisklein** [comment]
> I see, thanks. Is there any plan to fix this issue on homebrew?

not for the current releases as it will need a new ROOT version. Once the next FairSoft release is out (which we should verify on the latest Mac versions), then there will also be an update to the homebrew package.

**Comment by YanzhaoW** [comment]
While still waiting for a new fairsoft Homebrew formula, here is another failure caused by cmake 3.27 during Geant4 build. A relevant issue has already been reported [here](https://geant4-forum.web.cern.ch/t/issues-compiling-a-geant4-example-on-macos-incorrect-macro-invocation-in-geant4packagecache-cmake/10936). This failure can influence all versions of macOS as Homebrew only allows users to install the latest version of CMake (I have tested on macOS 12.6).

The second issue is uuid library contained in util-linux dependency. uuid library already exists in macOS and its header file is incompatible with the linux one. ROOT installation requires the macOS version of uuid. With util-linux being one of the dependencies, the installation would link ROOT to the linux version of uuid, thus causing a failure with the message "undefined type uuid_string_t".

**Comment by dennisklein** [comment]
Next legacy FairSoft release will contain at least [ROOT 6.30.2](f1b72b417e3dad0e616f1523392535ce0c52c66e), check the updated `dev` branch.

**Comment by fuhlig1** [comment]
@YanzhaoW,

did you test the latest FairSoft release jan24p2 (will come soon, fixes only a changed download link compared to jan24p1)?
Our test matrix shows that the compilation works with the latest version of macosx13 and macosx14.

**Comment by YanzhaoW** [comment]
@fuhlig1 

No, I haven't checked that. I will try it out and see whether it could fix the problem.
