### ISSUE TITLE
Cannot compile root6 on gcc6.2.1

### ISSUE THREAD

**Issue by bl0x** [FairRootGroup/FairSoft#50]
Since some time gcc does not allow used style of notation anymore.

Patch was introduced to ROOT already:
https://root.cern.ch/gitweb/?p=root.git;a=commitdiff;h=f12042c348941214ece48c19477f98e443a05862

Quoting from:
https://sft.its.cern.ch/jira/secure/attachment/18940/0001-Replace-0x1p-61-GNU-or-C-1z-with-pow-2-61.patch

> We cannot use `0x1p-61` when compiling with -std=c++11 or -std=c++14.
> This is only available starting -std=c++1z or if GNU extensions are
> enabled. This was a recent change in GCC 6.0.0 (Tue Mar 15 12:08:31
> 2016).

**Comment by MohammadAlTurany** [comment]
Fixed now in dev branch.
