### ISSUE TITLE
Use conan or vcpkg as the package manager?

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairSoft#500]
Hi,

Sorry if this is a stupid question. But why do we not use conan or vcpkg for FairRoot? They are the 2 most popular package managers among C++ projects in industries and they also integrate seamlessly with the cmake build system. I know spack is designed for the HPC system. However, we still have a lot of users who also need to run FairRoot in their own machines.

**Comment by fuhlig1** [comment]
@YanzhaoW,

since there was no action for more than one year I close the issue now. Please reopen it if there is more to discuss.
