### ISSUE TITLE
MacOS 13.5.1: cmake --build error

### ISSUE THREAD

**Issue by pgrusell** [FairRootGroup/FairSoft#506]
Hello,

I'm a macOS 13.5.1 user, using xcode-select version 2397 and Apple clang version 15.0.0. I encountered the following errors while attempting to perform a legacy installation of FairSoft, version nov22_patches:

1. `cmake -S /Users/pablogonzalezrusell/CODES/FAIR/FairSoft -B /Users/pablogonzalezrusell/CODES/FAIR/build  -C /Users/pablogonzalezrusell/CODES/FAIR/FairSoft/FairSoftConfig.cmake
`

loading initial cache file /Users/pablogonzalezrusell/CODES/FAIR/FairSoft/FairSoftConfig.cmake
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'version': Expected type T.nilable(MacOSVersion), got type Integer with value 0 (TypeError)

Despite encountering the error, I proceeded with the installation process as everything appeared to be functioning correctly.

2. `cmake --build /Users/pablogonzalezrusell/CODES/FAIR/build -j8`

[ 47%] Performing build step for 'boost'
CMake Error at /Users/pablogonzalezrusell/CODES/FAIR/build/Stamp/zeromq/zeromq-build-RelWithDebInfo.cmake:37 (message):
  Command failed: 2

   '/Library/Developer/CommandLineTools/usr/bin/make'

  See also

    /Users/pablogonzalezrusell/CODES/FAIR/build/Log/zeromq-build.log

-- Log output is: ...

And 

CMake Error at /Users/pablogonzalezrusell/CODES/FAIR/build/Stamp/boost/boost-build-RelWithDebInfo.cmake:37 (message):
  Command failed: 1

   './b2' '--layout=system' 'cxxstd=17' 'link=shared' 'threading=multi' 'variant=release' 'visibility=hidden' 'pch=off' '--site-config=/Users/pablogonzalezrusell/CODES/FAIR/build/site-config.jam' '-j 8'

  See also

    /Users/pablogonzalezrusell/CODES/FAIR/build/Log/boost-build.log

-- Log output is: ...

And 

[ 47%] Completed 'pythia8'
[ 47%] Built target pythia8
make: *** [all] Error 2

After encountering this issue, the building process came to a halt. I've made attempts to resolve the problem by also attempting installations of previous versions (e.g., apr22_patches), but unfortunately, the issue persists. If anyone has a viable solution, I would greatly appreciate your assistance.

Thank you in advance!

(I have attached the .log files for reference.)

[zeromq-build.log](https://github.com/FairRootGroup/FairSoft/files/13044683/zeromq-build.log)
[boost-build.log](https://github.com/FairRootGroup/FairSoft/files/13044686/boost-build.log)

**Comment by fuhlig1** [comment]
This is an issue reported also before on other channels. The problem obviously is XCode 15. The other user reported that downgrading XCode to version 14 helped in his case.

**Comment by pgrusell** [comment]
Indeed, downgrading the Xcode version actually solved the problem. Thank you very much.
