### ISSUE TITLE
Root 6.30/02 does not build on macOS 12 with AppleClang 14

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#511]
https://alfa-ci.gsi.de/job/FairRootGroup/job/FairSoft/job/legacy-update-ci/2/artifact/logs/macOS-12.7.1/root-build.log

```console
[ 76%] Generating G__Core.cxx, ../lib/Core.pcm
While building module 'Core':
While building module 'std' imported from input_line_1:1:
In file included from <module-includes>:31:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/complex.h:28:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/ccomplex:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/complex:235:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/cmath:642:26: error: missing '#include <limits>'; 'numeric_limits' must be declared before it is used
    bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/limits:443:28: note: declaration here is not visible
class _LIBCPP_TEMPLATE_VIS numeric_limits
                           ^
```

and many more similar ones, looks like missing entries in https://github.com/root-project/root/blob/master/interpreter/cling/include/cling/std.modulemap

**Comment by ChristianTackeGSI** [comment]
Should we [report](https://github.com/root-project/root/issues/) this to ROOT upstream?

**Comment by dennisklein** [comment]
Go ahead, if you have the stamina to follow through with it. I am personnally not motivated to fix this because I doubt there is any user running appleclang 14 on macos 12. I'd rather just update our ci image to macos 14 and appleclang 15 as a "solution".

**Comment by rbx** [comment]
Since we bump our test systems to 13/14, I would say this can be just closed. dev builds on those two.
