### ISSUE TITLE
Error when building Geant3: cannot find -lROOT::EGPythia6

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairSoft#514]
Hi

I'm trying to build FairSoft (latest in dev branch) in rhel 8.9 but get an error during the building process:

```shell
 cannot find -lROOT::EGPythia6
/opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -lROOT::EGPythia6
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/geant321.dir/build.make:17233: libgeant321.so] Error 1
make[4]: *** [CMakeFiles/Makefile2:110: CMakeFiles/geant321.dir/all] Error 2
make[3]: *** [Makefile:156: all] Error 2
```
I guess this comes from the building of Geant3. It looks like Pythia6 is not built with ROOT, which is required from Geant3.

**Comment by YanzhaoW** [comment]
I found a solution:

add `"-Dpythia6=ON"` to the ROOT cmake options among following lines:

https://github.com/FairRootGroup/FairSoft/blob/fae837212b17659c834ce928d5b0a58d4d15be0d/cmake/legacy.cmake#L346-L390

fixes the problem.

**Comment by dennisklein** [comment]
Yes, this option is missing. Thank you!

**Comment by fuhlig1** [comment]
@dennisklein,

this is already in my changes. There are also some other minor changes. I will probably commit today.
