### ISSUE TITLE
Missing log file

### ISSUE THREAD

**Issue by DanielWielanek** [FairRootGroup/FairSoft#52]
During installation I get following error:
-- Configuring incomplete errors occured!
See also ..../FairSoft/test/build/CMakeFiles/CMakeOutput.log
The problem is that this file is removed.

**Comment by MohammadAlTurany** [comment]
Hi Daniel,
Is this problem still there with the new FairSoft? it is almost two years (sorry for that!) I will close this issue, if you still have the problem please reopen it.

best,
Mohammad
