### ISSUE TITLE
FairSoft jan24 on Debian10

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairSoft#529]
The required cmake version for jan24 is at least 3.19 but with buster-backports on Debian 10 you only get 3.18. Thus the cmake stage of jan24 stops with:
```
CMake Error at cmake/legacy.cmake:8 (cmake_minimum_required):
  CMake 3.19 or higher is required.  You are running version 3.18.4
Call Stack (most recent call first):
  CMakeLists.txt:32 (include)
  ```
It would be great if a fix for this problem could be provided.

**Comment by ChristianTackeGSI** [comment]
I don't know, what raised it to exactly 3.19 (maybe DDS?).

Anyway: The solution is to install CMake from scratch. Either as a binary (see [here](https://github.com/FairRootGroup/FairSoft/blob/master/legacy/dependencies.md#bootstrapping-cmake), FairSoft has even a script to do that), or whatever method you like.

Not to mention, I'd recommend to move to at least Debian-11 (12 was released. so 10 is now not getting all security updates anyhow).

**Comment by fuhlig1** [comment]
@ChristianTackeGSI,

Debian10 is currently the default system at GSI, so I fear we will have more issues with that system. 😒

**Comment by fuhlig1** [comment]
Right, but we are not there yet. I hope this is only a matter of days but lets see.

**Comment by TobiasStockmanns** [comment]
Maybe it is more a documentation isssue. The requested CMake version in the docs (3.16.1) is not uptodate. Also the legacy/`setup_debian.sh` script only pushes you to CMake version 3.18.
I found the `bootstrap-cmake.sh` script only because I looked at your tested systems.

**Comment by ChristianTackeGSI** [comment]
Updating part of the docs is part of #521…

**Comment by fuhlig1** [comment]
You are right the cmake version in the docs is incorrect, but in the section 

https://github.com/FairRootGroup/FairSoft/blob/master/legacy/dependencies.md#bootstrapping-cmake

it is beside the wrong cmake version clearly described how to install a proper version using the script.
Please fell free to propose some better wording such that it becomes clearer what to do in case of an old cmake version.

**Comment by dennisklein** [comment]
> I don't know, what raised it to exactly 3.19 (maybe DDS?).

See https://github.com/FairRootGroup/FairSoft/commit/cb86cfc3d1852314059bcf354681a5d01253e60f

**Comment by RalfKliemt** [comment]
Hi there,

On a GSI Debia10 I also had to install `libprotobuf-dev` (error by dds cmake step). Would be a good idea to put it in the `setup-Debian.sh` script. I wonder if this would be an issue on the `lxi*` machines. 

The patch step for root is not robust against re-running the build command:
> [ 50%] Performing patch step for 'root'
> CMake Error at /data.local1/fairsoft_jan24/build/Stamp/root/root-patch-RelWithDebInfo.cmake:37 (message):
>   Command failed: 1
>
>   '/usr/bin/patch' '--merge' '-p1' '-i' '/data.local1/fairsoft_jan24/source/legacy/root/fix_macos_sdk_mismatch.patch'


An installation on cvmfs would be great, too.



Cheers!
  Ralf

**Comment by dennisklein** [comment]
> On a GSI Debia10 I also had to install `libprotobuf-dev` (error by dds cmake step). Would be a good idea to put it in the `setup-Debian.sh` script.

thx! added it.

> I wonder if this would be an issue on the `lxi*` machines.

> An installation on cvmfs would be great, too.

I'll pass your comment to @fuhlig1. If the upcoming cvmfs installation of FairSoft jan24 is meant to be used on lxi*, we should check that system packages are present.
 
> The patch step for root is not robust against re-running the build command:

For now, I disconnected the update step which should help in most re-run cases (as it does not trigger the patch step again any more), however, there might still be cases (e.g. when one updates the source or tag in an existing build dir that already ran the patch step). To solve this better we would probably need to wrap the patch command with some logic that first checks, if the patch is already applied and then only conditionally executes the actual patch. (wonder why the patch command itself does not have this option :( )

**Comment by fuhlig1** [comment]
@dennisklein, @RalfKliemt,

I will do a CVMFS installation soon. I am currently only waiting for the first patch release of jan24 which should be available soon.

**Comment by fuhlig1** [comment]
Currently an installation on CVMFS isn't possible. vae23 and vae24 are missing the now needed `ibprotobuf-dev`.

I requested already that the package is installed for both VAEs.

**Comment by dennisklein** [comment]
Was auto-closed by the update of the master branch. Re-opening as there are more issues collected in this thread.

**Comment by fuhlig1** [comment]
@RalfKliemt,

for debian10, debian11 and debian12 installation of FairSoft jan24p1 exist at

/cvmfs/fairsoft.gsi.de/<OS>/fairsoft/jan24p1/

Also  FairRoot installations are available at

/cvmfs/fairsoft.gsi.de/<OS>/fairroot/v18.8.2_jan24p1/

**Comment by fuhlig1** [comment]
I close the issue. In my opinion both topics (documentaion and standard installation on CVMFS) are done.
