### ISSUE TITLE
Installation with AlmaLinux9

### ISSUE THREAD

**Issue by jose-luis-rs** [FairRootGroup/FairSoft#536]
Hi
I would like to install FairSoft and FairRoot on AlmaLinux9 and I wonder if you have found any problems with this OS as it is not included in your CI matrix with Jenkins. Any comments?
Thanks

**Comment by dennisklein** [comment]
There is no specific to not have tested Almalinux other than we didn't know of any use case. But you asking for it is perfect, so I just added it to the test matrix, see #537. I also added a new `legacy/setup-almalinux.sh`. In principle, I don't expect major problems, let's wait, what the CI will report (https://cdash.gsi.de/index.php?project=FairSoft)

**Comment by dennisklein** [comment]
https://cdash.gsi.de/buildSummary.php?buildid=453181 - all good

You can build on Almalinux either from the `dev` or from `jan24_patches`, both contain the new `legacy/setup-almalinux.sh` script.
