### ISSUE TITLE
Error with the installation of FairSoft nov22p1 on Ubuntu 24.04

### ISSUE THREAD

**Issue by jose-luis-rs** [FairRootGroup/FairSoft#545]
Ubuntu 24.04
cmake 3.28.3
FairSoft nov22p1

FairSoft$ cmake --build ./build/ -j20
[  0%] Creating directories for 'zeromq'
[  0%] Creating directories for 'asio'
[  0%] Creating directories for 'clhep'
[  0%] Creating directories for 'vc'
[  0%] Creating directories for 'boost'
[  0%] Creating directories for 'faircmakemodules'
[  0%] Creating directories for 'fmt'
[  4%] Creating directories for 'pythia6'
[  4%] Creating directories for 'flatbuffers'
[  4%] Creating directories for 'hepmc'
[  4%] Performing download step (download, verify and extract) for 'vc'
[  4%] Performing download step (git clone) for 'zeromq'
[  9%] Performing download step (download, verify and extract) for 'boost'
[ 14%] Performing download step (git clone) for 'faircmakemodules'
[ 14%] Performing download step (download, verify and extract) for 'pythia6'
[ 14%] Performing download step (git clone) for 'asio'
[ 14%] Performing download step (download, verify and extract) for 'clhep'
[ 14%] Performing download step (download, verify and extract) for 'hepmc'
[ 14%] Performing download step (download, verify and extract) for 'fmt'
[ 14%] Performing download step (git clone) for 'flatbuffers'
CMake Error at /FairSoft/build/Stamp/zeromq/zeromq-download-RelWithDebInfo.cmake:37 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/FairSoft/build/tmp/zeromq/zeromq-gitclone.cmake'

  See also

    /FairSoft/build/Log/zeromq-download.log

-- Log output is:
Cloning into 'zeromq'...
fatal: unable to access 'https://github.com/zeromq/libzmq/': Could not resolve host: github.com
Cloning into 'zeromq'...
fatal: unable to access 'https://github.com/zeromq/libzmq/': Could not resolve host: github.com
Cloning into 'zeromq'...
fatal: unable to access 'https://github.com/zeromq/libzmq/': Could not resolve host: github.com
-- Had to git clone more than once: 3 times.

Can someone help to solve this problem?

Thanks in advance

**Comment by dennisklein** [comment]
> `Could not resolve host: github.com`

This indicates a problem of your computer accessing the [DNS](https://en.wikipedia.org/wiki/Domain_Name_System).

* If you experience this problem within the network of your research institute, I recommend to find assistance from your local network administrator.
   * Institute or company networks often grant access to internet services (such as DNS) via local proxy services. Your local network administrator should be able to confirm the availability of such proxy services as well as your computer having received the correct configuration (which usually happens automatically upon connecting to the network).
* If you experience this from a home network, this could e.g. be a result of a failed VPN connection - try a reboot and connecting to your network in a fresh user session.
* In general, such a problem is likely to be a temporary one. Try reconnecting to the given network at a later point in time.
* You can double-check the host name resolution in an easy way by just opening the url https://github.com in your favourite web browser.

This is very unlikely an issue of FairSoft, therefor closing. Feel free to re-open, once you exhausted the above hints/resources and it still fails with this error.

**Comment by jose-luis-rs** [comment]
Thanks, I am doing the installation on a new laptop and the network had failed for a while.

After solving this problem with the network, I found the same issue indicated in #544, but changing the path the installation continued up to get a new error:

`Performing build step for 'vc'
CMake Error at /FairSoft/build/Stamp/zeromq/zeromq-build-RelWithDebInfo.cmake:37 (message):
  Command failed: 2

   '/usr/bin/gmake'

  See also

    /FairSoft/build/Log/zeromq-build.log


-- Log output is:
[  1%] Building C object tests/CMakeFiles/unity.dir/__/external/unity/unity.c.o
[  1%] Building C object CMakeFiles/objects.dir/external/sha1/sha1.c.o
[  1%] Building C object CMakeFiles/objects.dir/src/tweetnacl.c.o
[  2%] Linking C static library ../lib/libunity.a
[  2%] Built target unity
[  2%] Building CXX object CMakeFiles/objects.dir/src/precompiled.cpp.o
[  2%] Building CXX object CMakeFiles/objects.dir/src/address.cpp.o
[  3%] Building CXX object CMakeFiles/objects.dir/src/channel.cpp.o
[  3%] Building CXX object CMakeFiles/objects.dir/src/client.cpp.o
[  3%] Building CXX object CMakeFiles/objects.dir/src/clock.cpp.o
[  4%] Building CXX object CMakeFiles/objects.dir/src/ctx.cpp.o
[  4%] Building CXX object CMakeFiles/objects.dir/src/curve_mechanism_base.cpp.o
[  4%] Building CXX object CMakeFiles/objects.dir/src/curve_client.cpp.o
In file included from /usr/include/c++/13/ext/alloc_traits.h:34,
                 from /usr/include/c++/13/bits/stl_tree.h:67,
                 from /usr/include/c++/13/map:62,
                 from /FairSoft/build/Source/zeromq/src/metadata.hpp:33,
                 from /FairSoft/build/Source/zeromq/src/msg.hpp:40,
                 from /FairSoft/build/Source/zeromq/src/curve_client.cpp:35:
/usr/include/c++/13/bits/alloc_traits.h: In instantiation of ‘struct std::__allocator_traits_base::__rebind<zmq::secure_allocator_t<unsigned char>, unsigned char, void>’:
/usr/include/c++/13/bits/alloc_traits.h:94:11:   required by substitution of ‘template<class _Alloc, class _Up> using std::__alloc_rebind = typename std::__allocator_traits_base::__rebind<_Alloc, _Up>::type [with _Alloc = zmq::secure_allocator_t<unsigned char>; _Up = unsigned char]’
/usr/include/c++/13/bits/alloc_traits.h:228:8:   required by substitution of ‘template<class _Alloc> template<class _Tp> using std::allocator_traits< <template-parameter-1-1> >::rebind_alloc = std::__alloc_rebind<_Alloc, _Tp> [with _Tp = unsigned char; _Alloc = zmq::secure_allocator_t<unsigned char>]’
/usr/include/c++/13/ext/alloc_traits.h:126:65:   required from ‘struct __gnu_cxx::__alloc_traits<zmq::secure_allocator_t<unsigned char>, unsigned char>::rebind<unsigned char>’
/usr/include/c++/13/bits/stl_vector.h:88:21:   required from ‘struct std::_Vector_base<unsigned char, zmq::secure_allocator_t<unsigned char> >’
/usr/include/c++/13/bits/stl_vector.h:428:11:   required from ‘class std::vector<unsigned char, zmq::secure_allocator_t<unsigned char> >’
/FairSoft/build/Source/zeromq/src/curve_client_tools.hpp:64:76:   required from here
/usr/include/c++/13/bits/alloc_traits.h:70:31: error: static assertion failed: allocator_traits<A>::rebind_alloc<A::value_type> must be A
   70 |                         _Tp>::value,
      |                               ^~~~~
/usr/include/c++/13/bits/alloc_traits.h:70:31: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
cc1plus: note: unrecognized command-line option ‘-Wno-tautological-constant-compare’ may have been intended to silence earlier diagnostics
gmake[5]: *** [CMakeFiles/objects.dir/build.make:202: CMakeFiles/objects.dir/src/curve_client.cpp.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:367: CMakeFiles/objects.dir/all] Error 2
gmake[3]: *** [Makefile:146: all] Error 2

CMake Error at /FairSoft/build/Stamp/zeromq/zeromq-build-RelWithDebInfo.cmake:47 (message):
  Stopping after outputting logs.


gmake[2]: *** [CMakeFiles/zeromq.dir/build.make:86: Stamp/zeromq/zeromq-build] Error 1
`

Any suggestions? 
Thanks in advance

**Comment by jose-luis-rs** [comment]
Sorry, I cannot re-open it.

**Comment by dennisklein** [comment]
What is your `gcc --version`?

From the output above it looks like you have version 13, I am afraid that FairSoft nov22 does not support GCC 13.

**Comment by dennisklein** [comment]
Sry, I am blind :P You wrote Ubuntu 24.04. Yes, unfortunately, nov22 does not support Ubuntu 24.04.

**Comment by jose-luis-rs** [comment]
Thanks @dennisklein, finally I have installed jan24_patches
