### ISSUE TITLE
Specifying -DCMAKE_INSTALL_PREFIX doesn't change the install prefix

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairSoft#549]
Hi,

I'm installing FairSoft-jan24p2. After unzipping the tar bar downloaded from the release page and configure the cmake with:

```cmake
cmake -DCMAKE_INSTALL_PREFIX=/opt/FairSoft/jan24p2 -S . -B ./build -C ./FairSoftConfig.cmake
```
The print out from the CMake still has:
```text
--   INSTALL PREFIX     /lustre/r3b/ywang/software/FairSoft-jan24p2/install (change with -DCMAKE_INSTALL_PREFIX=...)
```
which shows the install prefix is pointing to the default location, instead of the new location specified from the command line.

**Comment by dennisklein** [comment]
It seems the precedence of which `CMAKE_INSTALL_PREFIX` value is taken is determined by the command-line argument order, try
```
cmake -S . -B ./build -C ./FairSoftConfig.cmake -DCMAKE_INSTALL_PREFIX=/opt/FairSoft/jan24p2
```

**Comment by YanzhaoW** [comment]
I think the problem is caused by this line:
https://github.com/FairRootGroup/FairSoft/blob/5537f58e609219ec54b32fb766d7d705c7bef399/FairSoftConfig.cmake#L17

I feel this is a bit anti-pattern to hard-code a common cache variable in the script.

What's the problem to just set it without `FORCE`?

```cmake
set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/install" CACHE PATH "Install prefix") 
```
Then if a user provides any `CMAKE_INSTALL_PREFIX` by setting the flag in any position, this line will not overwrite the value.

**Comment by dennisklein** [comment]
I have no objections against removing the `FORCE` if that helps.

**Comment by fuhlig1** [comment]
@YanzhaoW,

did the removing of the FORCE solved your problem. If so please create a pull request with the requested change.

**Comment by YanzhaoW** [comment]
Hi,

Yes, I think so. I will create a PR about this.

**Comment by ChristianTackeGSI** [comment]
Can we close this as completed with #554?

**Comment by YanzhaoW** [comment]
yes, We can close this.
