### ISSUE TITLE
use git shallow clones

### ISSUE THREAD

**Issue by bl0x** [FairRootGroup/FairSoft#58]
To speed up installation process and reduce amount of diskspace used, please only do shallow clones of git repositories. This is safe for the users as they usually are not interested in the history of each piece of software.

**Comment by MohammadAlTurany** [comment]
Hallo,
Thanks for the info, we start using it but then we have problems with old "GIT" versions (delivered with Debian Jessie, meanwhile standard GSI installation!). As a work around we use now "Depth" to reduce the size.
Thanks.
Mohammad
