### ISSUE TITLE
Did ROOT break std::cout?

### ISSUE THREAD

**Issue by miharenthas** [FairRootGroup/FairSoft#67]
Hi,

Question: what do you make of this?

There was a crash (kSigSegmentationViolation).
This is the entire stack trace of all threads:

[...]

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.

#8  std::ostream::sentry::sentry (this=0x7ffe5f803f90, __os=...) at /usr/src/debug/gcc-7.2.1-20170915/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream.tcc:51
#9  0x00007f58c9016ee8 in std::__ostream_insert<char, std::char_traits<char> > (__out=..., __s=__s
entry=0x7f58d4a25075 "Loading Geant3 libraries ...", __n=28) at /usr/src/debug/gcc-7.2.1-20170915/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream_insert.h:82
#10 0x00007f58c9017377 in std::operator<< <std::char_traits<char> > (__out=..., __s=0x7f58d4a25075 "Loading Geant3 libraries ...") at /usr/src/debug/gcc-7.2.1-20170915/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/ostream:561
#11 0x00007f58d4a26144 in ?? ()
#12 0x00007ffe5f8040a0 in ?? ()
#13 0x00007f58ac8017be in cling::IncrementalExecutor::executeWrapper (returnValue=0x7ffe5f8046a0, function=..., this=0x2227dc0) at /usr/local/FAIR/FairSoft-roo6/tools/root/interpreter/cling/lib/Interpreter/IncrementalExecutor.h:197
#14 cling::Interpreter::RunFunction (this=<optimized out>, FD=<optimized out>, res=0x7ffe5f8046a0) at /usr/local/FAIR/FairSoft-roo6/tools/root/interpreter/cling/lib/Interpreter/Interpreter.cpp:916
#15 0x00007f58ac803d49 in cling::Interpreter::EvaluateInternal (this=this
entry=0x21d0590, input="g3libs()", CO=..., V=V
entry=0x7ffe5f8046a0, T=T
entry=0x0, wrapPoint=<optimized out>, wrapPoint
entry=0) at /usr/local/FAIR/FairSoft-roo6/tools/root/interpreter/cling/lib/Interpreter/Interpreter.cpp:1160
#16 0x00007f58ac803f7c in cling::Interpreter::process (this=0x21d0590, input="g3libs()", V=V
entry=0x7ffe5f8046a0, T=T
entry=0x0, disableValuePrinting=disableValuePrinting
entry=false) at /usr/local/FAIR/FairSoft-roo6/tools/root/interpreter/cling/lib/Interpreter/Interpreter.cpp:621
#17 0x00007f58ac8943b2 in cling::MetaProcessor::process (this=0x2430440, input_text=<optimized out>, compRes=
0x7ffe5f80469c: cling::Interpreter::kSuccess, result=0x7ffe5f8046a0, disableValuePrinting=<optimized out>) at /usr/local/FAIR/FairSoft-roo6/tools/root/interpreter/cling/lib/MetaProcessor/MetaProcessor.cpp:341
#18 0x00007f58ac7116bb in HandleInterpreterException (metaProcessor=0x2430440, input_line=0x7ffe5f8046f9 "g3libs()", compRes=
0x7ffe5f80469c: cling::Interpreter::kSuccess, result=0x7ffe5f8046a0) at /usr/local/FAIR/FairSoft-roo6/tools/root/core/metacling/src/TCling.cxx:1887

It looks like std::cout is the origin of the problem, by which I mean ROOT broke std::cout. A piece of evidence in favour of the broken std::cout hypothesis is that by getting rid of them in the macros interpreted (urgh) during the execution of my program all is well.

I'm on dev right now (which is on par with master, btw).

Cheers,
L.

**Comment by MohammadAlTurany** [comment]
Hi,
Is this Problem still there with the new ROOT? can you reproduce it with a small macro without FairRoot or it is related to FairRoot? how can we reproduce it?
