### ISSUE TITLE
Heads up: gfortran in GCC 8.1 changes behaviour

### ISSUE THREAD

**Issue by miharenthas** [FairRootGroup/FairSoft#86]
Hi,
This is a heads up, in case you didn't notice already: in GCC 8.1 gfortran will change behaviour in such a way that will prevent Geant321 from compiling, unless an additional flag *-std=legacy* is passed.

You can find the note here:
https://gcc.gnu.org/gcc-8/changes.html
"When an actual argument contains too few elements for a dummy argument, an error is now issued. The -std=legacy option can be used to still compile such code."

Note: I'm not on dev and not on the RC for this May. Yet. Right now I'm just trying to compile a somewhat old version on Fedora 28.

**Comment by MohammadAlTurany** [comment]
Thanks For reporting this, it is solved now and will go in the next release.
